caikit/caikit

README.md, pyproject.toml
- Add license and repo link to pyproject
- Use image link in README
=> :memo: Add license and repo to pyproject.toml

tests/core/data_model/test_producer.py
Small tests for current data model `ProducerId`
Addresses part of https://github.com/caikit/caikit/issues/15
=> :white_check_mark: Producer ID tests

docs/adrs/README.md
Populate the initial ADR readme
For #13
=> :memo: add ADR readme

CODEOWNERS, OWNERS
=> Update code owners file in GitHub

docs/architecture_club/04-25-23.md, docs/architecture_club/README.md
Starting some initial documentation of weekly maintainer meetings.
cc @hickeyma, we can move these out to google meet / google drive but this is pretty lightweight for us to get started
=> :memo: initial club meeting

CONTRIBUTING.md
Some small suggestions to the contribution guide to improve usability.
=> Updates to the contribution guide

docs/adrs/010-data-model-definition.md
=> :memo: Data model ADR

pyproject.toml
See https://github.com/caikit/caikit/pull/63
=> :arrow_up: unpin prometheus_client

caikit/core/data_model/streams/data_stream.py
=> 🐛 fix typo in example

.isort.cfg, README.md, examples/text-sentiment/README.md, examples/text-sentiment/client.py, examples/text-sentiment/models/text_sentiment/config.yml, examples/text-sentiment/requirements.txt, examples/text-sentiment/start_runtime.py, examples/text-sentiment/text_sentiment/__init__.py, examples/text-sentiment/text_sentiment/config.yml, examples/text-sentiment/text_sentiment/data_model/__init__.py, examples/text-sentiment/text_sentiment/data_model/classification.py, examples/text-sentiment/text_sentiment/runtime_model/__init__.py, examples/text-sentiment/text_sentiment/runtime_model/hf_block.py
Example which shows how a model is loaded and called from client code.
=> Add runtime example

examples/text-sentiment/text_sentiment/data_model/classification.py
Switch to the new `DataObjectBase` for the `text-sentiment` example
=> ♻️ fix example, switch to DataObjectBase

caikit/runtime/service_factory.py, pyproject.toml
This upgrades py-to-proto past a breaking api change in order to support streaming rpcs in the future
=> :arrow_up: Bump py-to-proto

docs/adrs/018-shared-backends.md, docs/adrs/019-loader-stack.md, docs/adrs/README.md
This PR introduces two ADRs related to the [shared backend PR changes](https://github.com/caikit/caikit/pull/97)
=> Shared backends adr

tests/core/data_model/test_dataobject.py
PR #103 removed an import that #107 required but both merged at the same time
=> :bug: Add missing import

caikit/runtime/service_generation/rpcs.py, tests/runtime/service_generation/test_rpcs.py
Requests with optional parameters were not getting generated
=> :bug: Fix request creation with optional params 

caikit/core/__init__.py
=> :bug: allow ModuleSaver/Loader import from core

README.md
Add a link to the excellent contributing.md into the main README to increase discoverability of the contributing guide.
=> Add link to contributing.md to the README

CONTRIBUTING.md, tox.ini
Changed the environment setup line in tox.ini file such that it dynamically detects python version of the user and uses that version as tox python environment. Also updated command in CONTRIBUTING.md
=> Small update: Tox file change

tests/conftest.py
For @gkumbhat 
This should allow us to run individual tests outside of `tests/core` again. Sorry about the regression!
=> :bug: fix test setup

releases.md
=> :memo: Add release process

tests/conftest.py, tests/runtime/test_grpc_server.py
This PR cleans up the unit tests so that they don't depend on running from the base of the repo and they don't create a `test` directory with a bunch of temporary files in them that don't get cleaned up on completion.
In general, we want to _always_ use `tempfile` for any interactions with disk in tests unless there is a concrete reason not to.
=> NoDanglingTestArtifacts: Use temp dirs instead of "test" everywhere

.github/workflows/build-library.yml, caikit/core/data_model/json_dict.py, tests/core/data_model/test_dataobject.py, tox.ini
=> Proto three fix 168

caikit/runtime/service_generation/rpcs.py, caikit/runtime/servicers/global_train_servicer.py, caikit/runtime/servicers/model_train_servicer.py, tests/runtime/service_generation/test_rpcs.py, tests/runtime/servicers/test_global_train_servicer_impl.py, tests/runtime/test_grpc_server.py, tests/runtime/utils/test_servicer_util.py
Train requests are now:  `${task}${module}TrainRequest`
Train calls are now: `${task}${module}Train`
Closes #165
=> 💥  Update train RPC names

examples/text-sentiment/client.py, examples/text-sentiment/text_sentiment/runtime_model/hf_module.py
* v0.7.0 requires tasks
Fixes: #184
=> Update examples/text-sentiment to work with v0.7.0

docs/adrs/001-module.md
Partial #13
Supersedes #155. Review comments in #155
=> Add module ADR

tests/runtime/servicers/test_global_train_servicer_impl.py
- Fix long running cancellation test
=> :bug: Remove manual training_id initialization

caikit/core/data_model/streams/data_stream.py, caikit/runtime/service_generation/data_stream_source.py, tests/core/data_model/streams/test_data_stream.py
This PR fixes #157 
Authored with copious input from @joerunde
=>  Fix: Closures in DataStreams prevent pickling

releases.md
=> Fix typo in releases.md file

README.md
Thanks @sumalaika for finding this issue.
=> Fix broken code of conduct link

caikit/core/modules/config.py, tests/core/modules/test_module.py, tests/core/test_model_manager.py
Closes https://github.com/caikit/caikit/issues/216
=> fix for old-style workflow id

caikit/interfaces/__init__.py, caikit/interfaces/nlp/__init__.py, caikit/interfaces/nlp/data_model/__init__.py, caikit/interfaces/nlp/data_model/package.py, caikit/interfaces/nlp/data_model/text_generation.py, caikit/interfaces/nlp/tasks.py, pyproject.toml, tests/interfaces/__init__.py, tests/interfaces/nlp/__init__.py, tests/interfaces/nlp/test_nlp_tasks.py
This PR adds the interfaces for Text Generation and Text Generation Streaming tasks
**NOTE:** These interfaces intentionally align closely with [Hugging Face Detail Parameters](https://huggingface.co/docs/api-inference/detailed_parameters#text-generation-task) and [Text Generation Inference](https://github.com/huggingface/text-generation-inference/blob/main/docs/openapi.json)
=> Text generation stream

caikit/core/data_model/dataobject.py, caikit/runtime/service_generation/data_stream_source.py, caikit/runtime/service_generation/rpcs.py, tests/core/data_model/test_dataobject.py
=> Make dataobject 252

caikit/core/data_model/base.py, tests/core/data_model/test_dataobject.py
Closes https://github.com/caikit/caikit/issues/256
Make sure that when inferring the which field from the python type, the  value of bool < int < float is respected
=> Handle type disambiguation for which_oneof

caikit/core/data_model/dataobject.py
This uses a `TypeVar` for the dataobject decorator, which addresses the first part of [Issue 227](https://github.com/caikit/caikit/issues/270). 
But the `TypeVar` does not fix the second issue, about type completion for the constructor.  I think the only solution for that is to add the `dataclass` decorator.  To that effect, I've adjusted the docstring for `dataobject`.
This PR also fixes some type inspection issues for the modified file, `dataobject.py` per principle of clean code practice (i.e. I would rather avoid submitting files with type check errors in them).
For [ai-foundation/watson-nlp-tracker/issue#](https://github.com/caikit/caikit/issues/270)
=> fix: Fix initial problems with typing of dataobject decorator

caikit/runtime/servicers/global_predict_servicer.py, tests/runtime/test_grpc_server.py
Closes #280 
The test here wasn't sufficient to make sure the correct message was created
=> :bug: fix error message on wrong inferece rpc

caikit/core/data_model/base.py, tests/core/data_model/test_dataobject.py, tests/fixtures/sample_lib/modules/sample_task/primitive_party_implementation.py, tests/runtime/test_grpc_server.py
This PR builds on top of https://github.com/caikit/caikit/pull/131 to provide the ability to have lists of `jsondict` types!
=> ♻️ jsondict list support

tests/core/toolkit/test_wip_decorator.py
I'm pretty sure that these sporatic errors are caused by the introduction of pytest-asyncio as a test plugin. The tests themselves were explicitly checking caplog.records[0], so if some other warning pops up during the capture, the regex check was failing. Since the consistent error has to do with the asyncio pool being closed, I suspect this is just a bad coincidence plus a test that's assuming it's more isolated than it is.
Closes https://github.com/caikit/caikit/issues/305
=> FlakeyWipTest: Convert tests to pytest and loosen regex match checks

caikit/core/toolkit/reversible_hasher.py, tests/core/toolkit/test_reversible_hasher.py
This will be used to obfuscate the trainer name in the ID given when submitting a training
Supports #308
=> Reversible Hasher

caikit/runtime/servicers/global_predict_servicer.py
fix https://github.com/caikit/caikit/issues/316
=> 🐛 fix output streams based on rpc metadata

caikit/runtime/service_generation/rpcs.py
We forgot to correctly set the input streaming flag on rpcs in a runtime service.
The actual invocations of the rpcs with streams is functional, but service reflection will not show an input stream
Fixes #320 
Waiting for a py-to-proto bugfix to land so that we can easily test this
=> :bug: correctly set streaming flags

caikit/runtime/http_server.py, tests/runtime/test_http_server.py
depends on https://github.com/caikit/caikit/pull/327
fixes #323 
This adds enum and list support to the rest server, so that it can return data models with enums or lists!
=> 🐛  Pydantic bug

caikit/runtime/http_server.py, tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py, tests/runtime/test_http_server.py
On top of https://github.com/caikit/caikit/pull/338
Taken inspiration from https://github.com/sysid/sse-starlette/blob/master/tests/test_event_source_response.py
fixes https://github.com/caikit/caikit/issues/340
=> ✅ Add REST server streaming test 

caikit/runtime/dump_services.py, examples/start_runtime_with_sample_lib.py
Closes https://github.com/caikit/caikit/issues/352
=> DumpHttpServices: Extend dump_services to also dump the HTTP spec

caikit/config/config.yml, caikit/runtime/servicers/global_train_servicer.py, tests/fixtures/config/config.yml
Make `save_with_id` configurable through the global config.
fix https://github.com/caikit/caikit/issues/362
=> 🚩 add save_with_id config

caikit/runtime/http_server.py, tests/runtime/test_http_server.py
Signed-off-by: Gabe Goodhart <ghart@us.ibm.com>
with help from Micah Goodhart ;)
=> HealthCheckOkResponse: Return an OK response from the health check

caikit/core/toolkit/destroyable.py, caikit/runtime/servicers/global_train_servicer.py, caikit/runtime/servicers/model_train_servicer.py, tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py, tests/runtime/servicers/test_model_train_servicer_impl.py
Closes #371 
Also fixes a little logging bug
=> :sparkles: redirect streams to training_input_dir

caikit/config/config.yml
This allows runtimes to set the `...IMPORT_CLASS` config in their environments
=> :bug: add import_class to default config yml

caikit/core/exceptions/caikit_core_exception.py, caikit/core/model_management/local_model_trainer.py, caikit/runtime/servicers/training_management_servicer.py, caikit/runtime/utils/servicer_util.py, tests/core/model_management/test_local_model_trainer.py, tests/runtime/servicers/test_training_management_servicer.py
=> Add CaikitCoreException 

caikit/core/data_model/base.py, caikit/core/data_model/json_dict.py, caikit/core/data_model/timestamp.py, caikit/core/exceptions/error_handler.py, caikit/core/model_management/local_model_trainer.py, caikit/core/model_management/model_trainer_base.py, caikit/core/toolkit/destroyable_process.py, caikit/runtime/servicers/training_management_servicer.py, tests/core/data_model/test_timestamp.py, tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py, tests/runtime/servicers/test_training_management_servicer.py
Closes #396
This does 3 things:
- Adds support for proto-ing timestamps in our data model
- Hooks up the submission and completion timestamps in the GetTrainingStatus api
- Fixes a bug in the local trainer where the completion time was unset
=> More training info

caikit/config/config.yml, caikit/runtime/grpc_server.py, caikit/runtime/http_server.py, caikit/runtime/server_base.py, caikit/runtime/servicers/global_predict_servicer.py, tests/core/toolkit/test_destroyable_thread.py, tests/fixtures/config/config.yml, tests/runtime/conftest.py, tests/runtime/servicers/test_global_predict_servicer_impl.py, tests/runtime/test_grpc_server.py, tests/runtime/test_http_server.py
Closes #387 
This PR makes it possible to enable/disable the auto-generated inference and training services in both the http and grpc servers
=> Optional services

caikit/runtime/servicers/training_management_servicer.py, tests/runtime/servicers/test_training_management_servicer.py
Wraps up #386 
This returns `CANCELLED` successfully when the underlying model future raises a not found error after cancellation
=> Handle trainers that cancel-by-delete

caikit/core/exceptions/caikit_core_exception.py, caikit/core/model_management/local_model_trainer.py, caikit/runtime/servicers/training_management_servicer.py, caikit/runtime/utils/servicer_util.py, tests/runtime/servicers/test_training_management_servicer.py
=> Add more exception codes

caikit/runtime/model_management/model_manager.py, tests/runtime/model_management/test_model_manager.py
=> LazyLoadEphemeralModels

caikit/interfaces/nlp/data_model/text_generation.py
Make `seed` optional for both unary and streaming text generation output data models
=> Make seed optional

caikit/runtime/__main__.py, caikit/runtime/dump_services.py, examples/sample_lib/start_runtime_with_sample_lib.py
- Only import respective stuff if it's enabled
- Added `try/catch` to all instances where we import `REST` or `gRPC` stuff so that user is shown a good error message
fix https://github.com/caikit/caikit/issues/457
=> 🐛 fix import logic

.gitignore
Add `.env` file that's needed by vs-code to add directories to `python_path`
Add `.env` to `.gitignore`. 
`.env` files are a way in VS-Code to add folders to Python path : https://caikit.github.io/website/docs/developing.html#vs-code-2
=> 🙈 Update .gitignore

examples/text-sentiment/client.py, tests/runtime/interceptors/test_caikit_runtime_server_wrapper.py, tests/runtime/servicers/test_global_predict_servicer_impl.py, tests/runtime/servicers/test_global_train_servicer_impl.py, tests/runtime/test_grpc_server.py, tests/runtime/test_service_factory.py, tests/runtime/utils/test_servicer_util.py
=> test: update tests to use datamodel classes

caikit/runtime/service_generation/data_stream_source.py, tests/runtime/service_generation/test_data_stream_source.py
Closes #480 with the alternative implementation of "try everything"
This is naive as, but it works
=> :sparkles: load files without extensions

caikit/runtime/servicers/global_train_servicer.py
- Fix duplicate logcode. As seen here: https://github.com/search?q=repo%3Acaikit%2Fcaikit%20%3CRUN490439039W%3E&type=code
=> Fix duplicate logcode

caikit/runtime/__init__.py, caikit/runtime/service_factory.py, caikit/runtime/service_generation/rpcs.py, examples/text-sentiment/client.py, tests/fixtures/sample_lib/__init__.py, tests/fixtures/sample_lib/modules/__init__.py, tests/runtime/servicers/test_global_predict_servicer_impl.py, tests/runtime/servicers/test_global_train_servicer_impl.py, tests/runtime/test_grpc_server.py, tests/runtime/test_service_factory.py
for https://github.com/caikit/caikit/issues/476.
Essentially, we should now be able to do this:
```
caikit.runtime.get_train_request(sample_module.modules.SampleModule)(
model_name=model_id,
parameters=get_train_params(sample_lib.modules.SampleModule)(
training_data=training_data
),
)
```
There are still some tests left that will need to be changed from `DataBase.get_class...` to this
=> ✨ add a better way to get request DMs

caikit/runtime/dump_services.py, tests/fixtures/config/config.yml, tests/runtime/test_dump_services.py
closes: #433 
Fixes bug where dumping http services failed if the output directory didn't already exist.
=> fix: dump http services, add tests

caikit/interfaces/nlp/data_model/classification.py, tests/interfaces/nlp/test_classification.py
Update ClassifiedGeneratedTextResult data model to mark certain parameters `Optional` and rename fields to be more user-friendly
=> Update ClassifiedGeneratedTextResult data model

caikit/runtime/servicers/training_management_servicer.py
=> :truck: Fix duplicate channel description

caikit/runtime/servicers/global_predict_servicer.py, caikit/runtime/servicers/global_train_servicer.py, tests/fixtures/sample_lib/modules/sample_task/list_implementation.py, tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py, tests/runtime/servicers/test_global_predict_servicer_impl.py
closes: https://github.com/caikit/caikit/issues/515
- Add support for handling grpc errors thrown by underlying backends.
=> Add rpc error handler

caikit/runtime/service_generation/protoable.py, tests/runtime/service_generation/test_protoable.py, tests/runtime/service_generation/test_rpcs.py
Currently we don't support a list of objects in method signatures. I'm not sure if this was intentional?
fix https://github.com/caikit/caikit/issues/519
=> 🐛 check protoable for list dm type

.github/workflows/publish-library.yml
Fix https://github.com/caikit/caikit/actions/runs/6670520388/job/18130767367
=> :bug: Tox install

pyproject.toml, tests/conftest.py, tests/runtime/test_dump_services.py, tests/runtime/test_grpc_server.py, tests/runtime/test_service_factory.py, tox.ini
Skip tests that dump protos when running with proto 3.X
=> SkipProtoSerialTestProto3

caikit/interfaces/nlp/data_model/classification.py, tests/interfaces/nlp/test_classification.py
This PR adds a warnings field and associated reason dataobject in order to have the ability to issue a warning when returning classification results.
=> added new dataobject for user warnings

tests/runtime/servicers/test_training_management_servicer.py
Wait for the model future to complete before asserting
=> FlakeyTrainingTest

caikit/runtime/servicers/info_servicer.py, tests/runtime/http_server/test_http_server.py
This PR adds support for supplying custom package names and versions to `runtime.version_info.python_packages`. This allows users to supply more detailed package information without supplying to much with `all`. 
=> Add support for custom package version info

caikit/runtime/http_server/http_server.py, tests/runtime/http_server/test_http_server.py
Related to issue: https://github.com/caikit/caikit/issues/570
=> Handle malformed json data for inference in http

.gitignore, examples/sample_lib/README.md, examples/sample_lib/client.py, examples/sample_lib/client_proto.py, examples/sample_lib/generated/__init__.py, examples/sample_lib/requirements.txt, examples/sample_lib/start_runtime_with_sample_lib.py, tests/examples/test_examples.py
This PR:
1. Adds a `client.py` to the `sample_lib` example package, so that users can interact with a python client to a running caikit runtime server.
2. Adds a `client_proto.py` to the `sample_lib` example package, that demonstrates how to use compiled `pb2s` along with the `DataModel` for a library (fix https://github.com/caikit/caikit/issues/470)
3. Updates documentation
This PR also tried to add a test for the `client.py` above, but until we figure out how to parallelize the tests, it's not worth adding it in because it takes a long time to set it up.
=> ✨ add a client for sample_lib

caikit/runtime/model_management/model_manager.py
This adds some operational visibility into the lazy load loop
=> :loud_sound: add lazy load loop debug logs

caikit/config/config.yml, caikit/runtime/model_management/model_manager.py, tests/runtime/model_management/test_model_manager.py
=> Configurable load wait 600

caikit/runtime/http_server/http_server.py, tests/runtime/http_server/test_http_server.py
fix https://github.com/caikit/caikit/issues/613
=> ♻️ don't wait for training jobs to finish when using http

caikit/runtime/model_management/model_sizer.py
- model sizer: fix exception f-string
=> fix exception f-string

caikit/core/modules/decorator.py, tests/core/test_task.py
Closes https://github.com/caikit/caikit/issues/624
Minor cleanup that I happened to find while poking around!
=> DoubleCountTasks: Don't re-add tasks from the class itself

caikit/runtime/http_server/http_server.py
=> FixHttpStatusLookup: Correct status code lookup dict

caikit/interfaces/common/data_model/file.py, caikit/interfaces/common/data_model/primitive_sequences.py, caikit/interfaces/common/data_model/producer.py, caikit/interfaces/runtime/data_model/info.py
This PR adds the `@dataclass` attribute to various DataBases include `File` and the `PrimitiveSequences`. This enables better type hinting and debugging
=> Add dataclass attribute to DataBases

caikit/interfaces/nlp/data_model/text_generation.py
Related to [PR](https://github.com/caikit/caikit/pull/671)
Add rank option to data model
=> Add ranks parameter to GeneratedToken

caikit/interfaces/common/data_model/remote.py
This PR adds support for non string GRPC options in the remote model finder.
=> Add Support for non string GRPC options

.gitignore, caikit/core/toolkit/name_tools.py, caikit/interfaces/runtime/data_model/model_management.py, caikit/interfaces/runtime/data_model/package.py, caikit/runtime/grpc_server.py, caikit/runtime/http_server/__init__.py, caikit/runtime/http_server/http_server.py, caikit/runtime/model_management/model_manager.py, caikit/runtime/names.py, caikit/runtime/service_factory.py, caikit/runtime/servicers/model_management_servicer.py, caikit/runtime/servicers/training_management_servicer.py, tests/runtime/conftest.py, tests/runtime/http_server/test_http_server.py, tests/runtime/model_management/test_model_manager.py, tests/runtime/test_grpc_server.py
Closes #579 
Closes #486 
This PR adds a new runtime `servicer` for model management with two new endpoints: `DeployModel` and `UndeployModel`. Additionally, it extends support for this service and the training management service to the `http_server`.
The logic of the `deploy`/`undeploy` is located in `caikit/runtime/model_management/model_manager.py` and centers around `local_models_dir`. These endpoints will raise errors if `local_models_dir` is not enabled.
This is a first-pass at a deploy mechanism that had known limitations, specifically for medium and large models. The immediate need for this feature is driven by Prompt Tune models from `caikit-nlp` which are extremely light and can easily be transmitted in …
=> Model service

caikit/runtime/train.py, tests/runtime/test_train.py
Adds .complete file to indicate to client who are watching the filesystem that we are done writing all of the files to disk. Also makes the termination log path configurable by environment variable.
=> Add .complete file, env var for termination log

caikit/interfaces/runtime/data_model/info.py, caikit/runtime/client/remote_model_finder.py, caikit/runtime/servicers/info_servicer.py, tests/runtime/client/test_remote_model_finder.py
This PR fixes a minor bug where the model_info endpoint would try to read info from a model that was still being loaded. 
=> Fix bug when fetching model info of partially loaded model
