- pyproject.toml
In Gabe's own words:
"Yes, it would allow a user to install unsafe versions, but it wouldn't require that a user do so and with pip it would automatically choose the latest semantic version that didn't conflict with other deps"
> ⬆️ expand protobuf compatible version

- pyproject.toml
Only `classifiers` are parsed - we will keep `license` in case pep changes
> :bug: Flit uses classifiers for license

- caikit/runtime/config/config.yml
- caikit/runtime/servicers/global_predict_servicer.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
Doing some config cleanup / feature pruning in support of https://github.com/caikit/caikit/issues/17
Before we provide one single config I wanted to remove as much as possible from the existing ones. This feature was added for one of the very first iterations of caikit to raise exceptions when models were called incorrectly. We have better ways of handling this now that services are generated from `caikit` itself instead of being run by hand-written proto files
> :fire: remove strict rpc mode

- caikit/runtime/config/config.yml
- tests/runtime/utils/test_configs.py
legacy config that wasn't deleted when we deleted the server's busy loop
> 🔥  remove grpc sleep interval

- caikit/runtime/service_generation/signature_parsing/parsers.py
- tests/runtime/service_generation/signature_parsing/test_parsers.py
For Issue #15 
What I assumed:
- We do not need "syntax_doc" and "raw_document" as KNOWN_ARG_TYPES
- I added "SampleOutputType" and "OtherOutputType" as KNOWN_OUTPUT_TYPES
This PR added more tests to increase the coverage for parsers.py
Before: 69%
After this PR: 100%
> test: Add more sig_parsing tests

- caikit/runtime/service_generation/primitives.py
- tests/runtime/service_generation/test_primitives.py
We don't want to throw in service generation even if the output type is not a DM object.
> 🐛 fix none output type

- caikit/runtime/service_generation/create_service.py
- caikit/runtime/service_generation/primitives.py
- caikit/runtime/service_generation/serializers.py
- tests/fixtures/sample_lib/blocks/other_task/other_implementation.py
- tests/runtime/service_generation/test_primitives.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
The introspection now picks the `primitive` or `primitive_data_model_types` from the `Union` as an arg to `.train` functions.
fix https://github.com/caikit/caikit/issues/51
> 🐛 handle union within train func args

- pyproject.toml
Pin dependency upper bounds to prevent potential breaking changes, `wheel` is not needed beyond test time
> :pushpin::heavy_minus_sign: Add dep upper bounds and remove wheel

- caikit/runtime/servicers/global_train_servicer.py
- tests/fixtures/sample_lib/blocks/sample_task/sample_implementation.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- Add subprocess exit code handling for training to allow capturing OOM type failures that kills the subprocess
> :sparkles: Add train process exit code handling

- caikit/core/data_model/base.py
- caikit/runtime/service_generation/create_service.py
- caikit/runtime/service_generation/signature_parsing/docstrings.py
- caikit/runtime/service_generation/signature_parsing/parsers.py
- tests/runtime/service_generation/signature_parsing/test_docstrings.py
- tests/runtime/service_generation/signature_parsing/test_parsers.py
- tests/runtime/service_generation/test_create_service.py
This PR is part of Issue #15
- refactors the 3 methods in `docstrings.py` that use 3rd party `docstring_parser.parse` [function](https://github.com/rr-/docstring_parser/blob/master/docstring_parser/parser.py#L23) to instead of checking for None, handle the `ParseError` exception. 
- adjusts the tests to mock the exception raised. I don't think we ever get this exception because we call `docstring_parser.parse` with Auto style, we always get a Docstring object back, albeit a Docstring object with empty params.
- add more tests to increase docstring test coverage:
**Updated:**
- When handling `ParseError` exception, this PR adds a raise for `CaikitRuntimeException` and lets the callers of those 3 methods in `parsers.py` decide what to do with that exception. In this case, these callers log …
> test: Docstrings module tests

- caikit/runtime/grpc_server.py
- tests/conftest.py
- tests/runtime/test_grpc_server.py
This is a public API and the shortened names are more difficult to understand
> :truck: Rename grpc server params

- caikit/runtime/grpc_server.py
- tests/runtime/test_grpc_server.py
The `signal.signal` interface has a second argument:
> The handler is called with two arguments: the signal number and the current stack frame
REF: https://docs.python.org/3/library/signal.html#signal.signal
Without this change, sending a signal to the server process results in a stack trace with:
```
TypeError: interrupt() takes 2 positional arguments but 3 were given
```
> :bug: add second argument to interrupt()

- caikit/runtime/grpc_server.py
- caikit/runtime/utils/import_util.py
2 changes:
1. `grpc_server.py`:
Doesn't make sense to have `log.error` for this statement since we still go forward with the initialization of the grpc server even if train service doesn't exist?
2. `import_util.py`:
Doesn't make sense to `log.error` _and_ throw an exception?
> ♻️ warning message for missing train service

- caikit/runtime/grpc_server.py
Closes #92 
This checks if the socket path exists before trying to bind to it. Should reduce the amount of error logs when sockets aren't being used
> :bug: check for socket file first

- caikit/core/__init__.py
- caikit/core/data_model/__init__.py
- caikit/core/data_model/base.py
- caikit/core/data_model/dataobject.py
- caikit/core/data_model/producer.py
- caikit/interfaces/common/data_model/producer.py
- caikit/interfaces/runtime/data_model/training_management.py
- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/data_stream_source.py
- tests/core/data_model/test_base.py
- tests/core/data_model/test_dataobject.py
- tests/data_model_helpers.py
- tests/fixtures/sample_lib/data_model/sample.py
- tests/runtime/service_generation/test_data_stream_source.py
The [discussion on the `dataclass_to_proto` PR](https://github.com/caikit/caikit/pull/86#discussion_r1183077788) brought up a really interesting point that injecting base classes with a decorator is confusing at best and an anti-pattern at worst.
This PR attempts to fix that by having a new base class for all data model classes that use `@dataobject`: `DataObjectBase`.
The crux of this PR is lifting the logic for parsing the protobuf descriptor out of the `__new__` function on `_DataBaseMetaClass` and allowing it to be called from within `@dataobject` once the proto class has been generated. This required some fancy footwork with a new `metaclass`/base class pair: `_DataObjectBaseMetaClass`/`DataObjectBase`. The only logic that couldn't be hoisted out of `_DataBaseMetaClass.__new__` was …
> Data object base

- caikit/core/data_model/streams/data_stream.py
- tests/core/data_model/streams/test_data_stream.py
- tests/fixtures/data_stream_inputs/control_chars.jsonl
- tests/fixtures/data_stream_inputs/control_chars_jsonl.jsonl
Handle escaped control characters in the server while loading training data.
The current code handles control characters as part of the string, for example `"name \t ": "John"` works well. But introducing new line characters as part of a `jsonl` file is what's causing problems at the moment.
> 🐛 handle ctrl chars in datastream

- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/create_service.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/service_generation/serializers.py
- tests/runtime/test_service_factory.py
This PR:
- Moves the logic for the below from `service_factory` into `serializers`:
```
def create_request_data_model() -> Type[DataBase]:
def create_rpc_json() -> Dict:
```
- Adds a few more tests for `service_factory` test coverage
Closes https://github.com/caikit/caikit/issues/53
> Refactor serializers (and service factory)

- caikit/core/model_manager.py
- caikit/core/module_backend_config.py
- caikit/core/module_backends/base.py
- tests/core/helpers.py
- tests/core/test_model_manager.py
- tests/core/test_module.py
- tests/core/test_module_backend_config.py
This PR walks back an accidental API breaking change in `0.4.0` where we added `name` as a required initializer arg to `BackendBase`. We had decided to remove this since it's not actually necessary and it adds additional awkwardness, but forgot to make the change before merging and cutting `0.4.0`.
> 🐛  Fix name in shared backends

- caikit/config/config.py
- caikit/config/config.yml
- caikit/core/module_backend_config.py
- tests/config/test_configs.py
- tests/conftest.py
- tests/core/data_model/test_dataobject.py
- tests/core/test_model_manager.py
- tests/core/test_module_backend_config.py
- tests/core/workflows/test_base.py
- tests/runtime/model_management/test_model_manager.py
- tests/runtime/test_grpc_server.py
- Allow for "merge" (prepend for lists, deep merge for dicts) or "override" merge strategies via a new configuration key
- Remove `disable_local` since we don't want anymore special handling for the local module backends. The default values will include `LOCAL`
- ~~Supply backend name to tests so that multiple Mock backend types will not conflict - we will plan to remove name-based lookup semantics in the near future as backends are not accessed by name except in tests~~
Addresses part of #102
> :sparkles: Add config merge strategy

- CODEOWNERS
Quick PR to add @tharapalanivel & and I to the codeowners. 😄
> Add missing maintainers to codeowners

- .github/workflows/lint-code.yml
- tox.ini
PR checks are having issues because:
- pydeps needs `dot` installed
- some weird bug with 1.12.5 crashes :(
> :bug: install graphviz/dot

- caikit/core/model_manager.py
- tests/core/test_model_manager.py
- tests/runtime/model_management/test_model_loader.py
This PR is a little bugfix to supply the concrete load backend as a kwarg to `.load` classmethods on alternative backend module implementations.
This is to support users who need to have access to the load backend at initialization time. Previously they used `caikit.get_backend(type)` but this was removed in favor of explicitly setting the load backend. For shared load backends this is fine, but for backend-specific module implementations this deferred knowledge of the backend until post initialization. 
We have some design work to do to fix this gap, but in the meantime a quick extra kwarg to load will unblock us.
> 🐛  Load backend arg

- caikit/core/data_model/base.py
- tests/core/data_model/test_dataobject.py
The problem is the fact that when we have
```
@dataobject
class BazObj(DataObjectBase):
@dataobject
class Foo(DataObjectBase):
data: List[str]
@dataobject
class Bar(DataObjectBase):
data: str
data_stream: Union[
Annotated[Foo, FieldNumber(1), OneofField("foo")],
Annotated[Bar, FieldNumber(2), OneofField("bar")],
]
```
During the `from_proto` -> since `foo` and `bar` are part of `cls._fields_message`, we do the `if proto.HasField(field): `check before setting the value of the field. So in this case, we don’t set the value of `bar`.
But, in the case of
```
@dataobject
class Foo(DataObjectBase):
foo: Union[
Annotated[int, FieldNumber(10), OneofField("foo_int")],
Annotated[float, FieldNumber(20), OneofField("foo_float")],
]
```
since both `foo_int` and `foo_float` are in …
> 🐛 handle from_proto oneof case

- caikit/core/modules/base.py
- tests/core/modules/test_module.py
For @gkumbhat
This puts back the old workflow base load as the module base load, so users that implement only `_load` aren't broken
> :bug: put default load impl back

- examples/text-sentiment/client.py
Fix to client code as client stubs changed following the module flattening in release [v0.5.0](https://github.com/caikit/caikit/releases/tag/v0.5.0)
Thanks @afrittoli for finding this bug.
**Notes for Reviewers:**
- Going to push a test PR for the example following this fix. Think it is best to get this fixed first asap.
> Fix text sentiment example after api change v0.5.0

- caikit/core/data_model/base.py
- tests/core/data_model/test_dataobject.py
```
class Foo(DataObjectBase):
foo: Union[
Annotated[int, FieldNumber(10), OneofField("foo_int")],
Annotated[float, FieldNumber(20), OneofField("foo_float")],
]
```
```
foo1 = Foo(foo_int=2)
json_repr_foo = foo1.to_json()
assert json.loads(json_repr_foo) == {
"foo_int": 2,
"foo_float": None,
}
```
`"foo_float": None` should not be in the `to_json` representation.
> ♻️ ignore unset fields in to_dict

- caikit/core/data_model/base.py
- caikit/core/data_model/dataobject.py
- caikit/core/data_model/json_dict.py
- tests/core/data_model/test_dataobject.py
- tests/core/data_model/test_json_dict.py
This PR adds a new data model utility to support type hinting and proto serialization for arbitrary json-serializable dicts
* Add the new `caikit.core.data_model.json_dict` module containing the `JsonDict` type definition and `dict_to_struct`/`struct_to_dict` converter utilities
* Add support in `ModuleBase` to detect `Struct`/`JsonDict` fields and convert accordingly in `to_proto`/`from_proto`
> Jsonable dicts

- tests/base.py
- tests/conftest.py
- tests/core/data_model/test_dataobject.py
- tests/core/helpers.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
- tests/runtime/servicers/test_model_runtime_servicer_impl.py
- tests/runtime/work_management/test_destroyable_thread.py
Fix unit test warnings related to:
- deprecations
- unhandled thread exceptions
The only warnings left are related to a caikit deprecation: caikit/core/modules/config.py:66: DeprecationWarning: No module_id found in config.
This cleans-up the log output and makes it easier to detect new warnings.
> Fix most unittest warnings

- caikit/runtime/grpc_server.py
- caikit/runtime/interceptors/caikit_runtime_server_wrapper.py
- pyproject.toml
- tests/runtime/test_grpc_server.py
- tox.ini
Closes #156 
This PR enables service reflection, finally!
As a side-effect, this also fixes a bug where all streaming RPCs were dropped from the server. This meant that at least the grpcio-healthchecking's `Watch` rpc did not work, it would error with a `None is not callable` message. We never knew that this was a problem before, but having `None` handlers registered with the server will blow up when you try to build a descriptor pool using the reflection api.
This _also_ removes the `excluded_methods` kwarg for the server wrapper initializer, it was an unused feature that would skip setting the `global_predict` handler on a given set of rpc names in a service. It wasn't tested and I don't think we'll need it so.... might as well bump the coverage because YAGNI
With this change, here is …
> ✨ Enable service reflection

- caikit/core/data_model/base.py
- caikit/core/data_model/data_backends/base.py
- caikit/core/data_model/data_backends/dict_backend.py
- tests/core/data_model/test_dataobject.py
This PR adds a new return type option for data backends' `get_attribute` that will allow for the backend to return the `oneof` value along with information on which of the `oneof` fields is currently set.
* Add a new helper struct `OneofFieldVal` in `DataBase` that holds the `oneof` value and the corresponding `which_oneof` 
* If `OneofFieldVal` is returned from a backend, use the information from the struct to set the appropriate `which_oneof` value
* Make required changes in `DictBackend` to test this functionality
> WhichOneof from Backend

- caikit/core/signature_parsing/parsers.py
Improving this warning: "Could not deduct output type from function %s for module class %s."
* Log fn.__name__ (e.g. train) which is more useful than a signature like () or (*args, **kwargs)
* Don't log warning for functions in the base module
- Because it is too spammy for optional overrides like train()
- It'll be obvious enough if these functions are accidentally called at runtime
- Keep and enhanced version of the message using log.debug for the base method case.
Fixes: #177
> Improve warning message and suppress it for base functions

- caikit/config/config.yml
- caikit/core/task.py
- caikit/runtime/service_generation/create_service.py
- caikit/runtime/service_generation/primitives.py
- caikit/runtime/service_generation/protoable.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/service_generation/type_helpers.py
- examples/text-sentiment/text_sentiment/config.yml
- tests/core/test_task.py
- tests/fixtures/sample_lib/config.yml
- tests/runtime/service_generation/test_primitives.py
- tests/runtime/service_generation/test_protoable.py
- tests/runtime/service_generation/test_rpcs.py
This PR deletes all the gorpy `is_primitive` logic and the ever confusing `runtime.service_generation.primitive_data_model_types` configurations.
As a follow-on to #167, this should actually finish up #90 and help with #30
This is all made possible by the explicit `tasks`, which now validate up-front that a module has the required input parameters and output type. The remainder of the work at service-generation time is to strip any non-protobufable args out of the request messages, which has much simpler implementation logic than what we were previously doing
> 💥 Remove primitive configs

- .github/workflows/build-library.yml
- .gitignore
- tox.ini
Add coverage report thanks to the python-coverage GitHub action https://github.com/marketplace/actions/python-coverage
The action reports the coverage as a GitHub comment. It also allows defining thresholds for the level of coverage. For now, setting an 80% thresholds for new files and zero for existing content. Once the report is published to PRs we can start working on bringing the coverage up to the desired level and enable the threshold for existing code.
We run unit tests for four different versions of python, but I don't think we need coverage for each.
Nonetheless, I changed the tox.ini to make sure that the coverage reports from the four runs do not override each other, and produce both html and xml reports.
Html is convenient when running locally, xml is needed by the action.
The …
> Add coverage report and threshold

- .github/workflows/build-library.yml
Looks like while this fails we're seeing other build checks be cancelled, just quickly commenting out the coverage pushing for now until there's a fix
> :bug: undo coverage while it's being fixed

- .github/workflows/build-library.yml
The coverage action does not support push events.
Only run the coverage step on pull_request.
> Run coverage on pull_request only

- .github/workflows/build-library.yml
The coverage action does not get the correct permissions in the GITHUB_TOKEN on PRs from non-maintainers, so dropping it for now.
> Drop the coverage action

- caikit/runtime/service_factory.py
cleanup we missed when we deleted the compiled proto service support
> :fire: delete unused compiled proto helpers

- README.md
caikit has passed the OpenSSF basic level as `passing`. We want to display the badge in the README as standard practice.
Result from this [issue](https://github.com/caikit/caikit/issues/152)
> Display OpenSSF Badge

- caikit/runtime/service_factory.py
- caikit/runtime/servicers/global_predict_servicer.py
- tests/conftest.py
- tests/fixtures/sample_lib/modules/sample_task/inner_module.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
This PR adds some more robust checks that the module loaded for inference is supported by the inference rpc invoked.
This should actually be helpful for users, so that they don't just get serialization errors back when they invoke the wrong rpc for a model. (Which I just did and floundered around for a while wondering what was wrong).
Closes #215
> :sparkles: Add rpc validation on inference

- caikit/runtime/work_management/train_executors.py
- Currently the local thread executor is incorrectly calling `cancel` function when getting to `__del__` function at the end. This will cause false alarms where training gets successfully completed but at the end we would see `Terminated` error message, which can cause confusion.
- Add fix to overcome python3.9-3.11 bug where if you create a subprocess inside a ThreadPoolExecutor then it will always exit with `exitcode` 1 thus signaling error.
> :bug: Fix incorrect cancellation of training request for thread executor

- pyproject.toml
- tests/core/data_model/data_backends/test_dict_backend.py
- tests/core/data_model/test_base.py
- tests/core/data_model/test_dataobject.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
- tests/runtime/utils/test_servicer_util.py
⬆️ bump `py-to-proto` to 0.3.x
This adds an underscore between the field name and the type for generated oneof field names
> 💥  API changes for py-to-proto 0.3.x

- caikit/core/data_model/dataobject.py
- tests/core/data_model/test_dataobject.py
Closes #210 
This PR makes it possible for classes to inherit from `@dataobject` classes and only override functionality without overriding the fields.
As written, the `_proto_class` for the derived class will be a different protobuf object with a matching schema. If the goal here is to be able to have private server-side overrides with public client-side schemas (which I believe is what @tharapalanivel and @prashantgupta24 need), we may need to dig further on whether we can fully reuse the `_proto_class`. This would potentially cause conflicts when trying to look up the data model class for a given proto, though.
> Dm function inheritance 210

- caikit/runtime/servicers/global_predict_servicer.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
Closes #223 
This PR splits out the core inferencing logic from the `GlobalPredictServicer`'s `Predict` function so that it can be called directly with the data model objects. This is needed to allow a REST server to reuse the same inferencing logic as the grpc server.
> Split global predict servicer

- caikit/core/module_backends/local_backend.py
For @evaline-ju 
The context is that this warning could be misleading for any `caikit` module users. While the local backend is registered by default. the "WIP" (work in progress/beta) message shows up in any library using caikit, and individual caikit library module users would not be dealing with the backend directly.
> :mute: remove WIP warning on local backend

- .github/workflows/build-library.yml
- .readthedocs.yaml
- caikit/core/signature_parsing/docstrings.py
- docs-requirements.txt
- pyproject.toml
- tests/conftest.py
- tests/runtime/conftest.py
- tests/runtime/test_grpc_server.py
- tox.ini
This PR sets up the framework for optional dependencies in `caikit` and refactors the existing dependency management into the following sets:
Closes: #228 
* `caikit`: Dependencies for `caikit.core`
* `caikit[runtime-grpc]`: Dependencies for the `grpc` runtime
* `caikit[all]`: All dependencies for user functionality in `caikit` (currently core + `runtime-grpc`)
* `dev-test`: Dependencies for running unit tests
* `dev-docs`: Dependencies for building documentation
* `dev-fmt`: Dependencies for formatting, linting, and other stylistic checks
* `dev-build`: Dependencies for building the wheel
* `all-dev`: All developer dependencies (including all user dependencies)
**NOTE**: The choice of `-` as a delimiter seems to be required when using `flit` as our build tool. I had originally used `.` …
> Optional deps 228

- .github/workflows/build-library.yml
- examples/text-sentiment/client.py
- pyproject.toml
- tests/examples/shared.py
- tests/examples/test_examples.py
- tox.ini
Add e2e test for examples
Add an e2e test for the text sentiment example.
The test is written as a standard python test so it can be
discovered by pytest and all the nice python tooling for
tests works as usual.
The test creates a new virtual environment and installs
caikit from the local disk, to ensure it tests the version of
caikit from the pull request (or local code changes).
The test then follows the same process described in the README:
- installs requirements.txt
- runs the start_runtime.py script
- runs the client.py
This test ensures that the example stays in a working state.
The example is likely to be one of the first points of contact
of people looking at caikit and it should always be working.
This test also helps in detecting unintended API changes.
Eventually we should …
> Add E2E coverage to example scenarios

- examples/text-sentiment/requirements.txt
- tests/examples/shared.py
Caikit needs to be installed with "pip install caikit[all]". Add "[all]" to the example requirements.txt to fix the example and to the examples test as well.
The change in the requirements configuration was merged before the example test was, so main is now broken.
This change also remove the delelopment mode from the pip command in the test examples, since it does not work without a setup.py from python3.9 and earlier.
> Fix example and test

- caikit/core/toolkit/sync_to_async.py
- pyproject.toml
- tests/core/toolkit/test_sync_to_async.py
Closes #224 
Depends on #241 
This PR adds a utility for wrapping synchronous iterators as `async` generators. It is needed for support of SSE streaming in the HTTP server.
> Sync to async iter wrapper 224

- caikit/runtime/service_generation/data_stream_source.py
Import `caikit.interfaces.common` explicitly in `caikit/runtime/service_generation/data_stream_source.py` since this module needs it.
> 🐛 caikit.interfaces.common bug fix

- caikit/core/toolkit/factory.py
- tests/core/toolkit/test_factory.py
This PR adds a simple `Factory` that can be reused across different config-oriented factory objects. There's not a lot of code, but it does make explicit that the `"type"` and `"config"` strings should be used and how they should be organized, so it's worth standardizing as the number of factories grows.
Supports: https://github.com/caikit/caikit/issues/54
> Add a basic base factory to codify factory keys and semantics

- caikit/runtime/model_management/training_manager.py
- tests/runtime/model_management/test_training_manager.py
The test was flakey because it was hitting a race where the future had not yet started or completed and fell through to the Unexpected Error below. That error was there to handle shutdown and cancellation which seems unnecessary.
Closes: https://github.com/caikit/caikit/issues/258
> Don't error out of the training manager when not started

- caikit/core/data_model/streams/validator.py
- caikit/core/modules/base.py
- caikit/core/toolkit/quality_evaluation.py
- caikit/runtime/model_management/model_sizer.py
- caikit/runtime/work_management/destroyable_thread.py
- scripts/dsconverter.py
- scripts/test_dsconverter.py
Addressing an edge case I didn't notice during initial PR #211. arg_replacement function would sometimes append the word "None" in front of an argument when it shouldn't have been there. This is because in another edge case where there is a description but no data type, I forgot to include the case that there might not be additional description past the first line. I also went back and manually fixed where "None" was appended in docstrings from the previous PR.
> Fix None edge case of docstring converter

- caikit/interfaces/common/data_model/producer.py
- tests/interfaces/common/test_producer.py
Closes: #292 
Removing the init since dataobject decorator should do init. The custom logic is not particularly needed here, also adding tests
> 🐛 Add back producers for producer priority

- caikit/runtime/work_management/train_executors.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- Fix `set_train_location` fixture, which was not setting the `sample_train_servicer.use_subprocess` value correctly because:
1. The format of config had changed
2. The scope of `sample_train_servicer` was `session`, so the value of use_subprocess was not getting changed by test. Additionally, the GlobalTrainServicer interacts with service generation etc, changing the scope to `function` for this fixture would create errors.
- The `error` in `_ErrorCaptureProcess` was actually never getting set in case of exception. The reason for that is after forking another process, the instance with parent process of `_ErrorCaptureProcess` will not be same as with the child process. So even if child process sets the value of `self.error` it will not get propagated to the parent and thus the …
> 🐛 Fix multi-processing exception handling and train_location_handling fixture

- caikit/core/task.py
- caikit/runtime/service_generation/create_service.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/servicers/global_predict_servicer.py
- tests/core/test_task.py
- tests/runtime/service_generation/test_create_service.py
- tests/runtime/service_generation/test_rpcs.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
The current inference service generation code assumes that a module has a single inference method, and RPCs are built by collecting those inference methods.
This PR takes into account all the @taskmethods on each module. RPCs are generated for each (task, supported streaming flavor) combo!
This PR also generates a request message for the task that only includes the type for the parameter given by the task definition
fix https://github.com/caikit/caikit/issues/284
fix https://github.com/caikit/caikit/issues/217
> ♻️ refactor RPCs for streaming

- caikit/core/task.py
- caikit/runtime/interceptors/caikit_runtime_server_wrapper.py
- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/protoable.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/servicers/global_predict_servicer.py
- caikit/runtime/utils/servicer_util.py
- tests/fixtures/sample_lib/data_model/sample.py
- tests/fixtures/sample_lib/modules/__init__.py
- tests/fixtures/sample_lib/modules/geospatial/__init__.py
- tests/fixtures/sample_lib/modules/geospatial/geo_streaming_module.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/conftest.py
- tests/runtime/service_generation/test_create_service.py
- tests/runtime/service_generation/test_protoable.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
Mostly addresses #287 
This adds grpc api support for input streams, allowing all 4 flavors of streaming to be used.
This is a little bit rough at the moment to get things out the door, we'll be following up with integration into https://github.com/caikit/caikit-nlp and fixing edge cases as they pop up.
A known issue here is that we check if the output of a model is iterable to determine whether or not to stream the output, but that information should come from the rpc metadata instead.
> ✨ Support input streams in servicer

- tests/runtime/conftest.py
Use `os.path.join` instead of hardcoding output proto dir path.
Also optionally generates the `inference_service`/`train_service` proto file!
> 🐛 use path.join

- README.md
- examples/text-sentiment/README.md
- examples/text-sentiment/start_runtime.py
Along with a couple of doc edits for readability, this PR addresses #235 to ensure that the text-sentiment example can be followed successfully without specifying a directory to run the `start_runtime.py` script from by overwriting the default value for `local_models_dir` to be a deduced absolute path of the script.
> Update example and documentation

- examples/text-sentiment/client.py
- examples/text-sentiment/start_runtime.py
- examples/text-sentiment/text_sentiment/runtime_model/hf_module.py
- tox.ini
This fixes the errors that will show up with tox after #196 is merged
The arguments differ problem is due to the way ModuleBase is defined.  I think disabling on each line is best fix so we still have that check elsewhere.  Is there a better fix?
Also I'm disabling the import error on transformers because I haven't found a convenient way to ensure we have the example requirements (and don't want to install transformers for now).
> Format and lint examples

- caikit/config/config.yml
- caikit/core/model_management/factories.py
- caikit/core/model_management/local_model_trainer.py
- caikit/core/model_management/model_trainer_base.py
- caikit/core/toolkit/destroyable_thread.py
- tests/core/helpers.py
- tests/core/model_management/__init__.py
- tests/core/model_management/test_local_model_trainer.py
- tests/core/toolkit/test_destroyable_thread.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
This PR adds the `LocalModelTrainer` implementation of the `ModelTrainerBase` abstraction so that `caikit.train` can use it. It is configurable to use either a `DestroyableThread` or a `DestroyableProcess` to perform the asynchronous training job.
Closes #308 
**Upstream PRs**
* https://github.com/caikit/caikit/pull/304
* https://github.com/caikit/caikit/pull/288
* https://github.com/caikit/caikit/pull/309
> Local trainer

- examples/text-sentiment/README.md
- examples/text-sentiment/client.py
- examples/text-sentiment/requirements.txt
- examples/text-sentiment/start_runtime.py
- pyproject.toml
- tox.ini
For the non-bug part of #323 
This adds a `--protocol` flag to the example scripts to run the http server as well.
This does not yet fix the bug in the http server itself, where the response for this huggingface model is not returned. I hope to get to that soon, just wanted to get this example out here and then come in with a fix and tests.
> :sparkles: add http example

- caikit/runtime/http_server.py
Closes: #344 
The assumption for the http server had been that `run` and `run_stream_out` would be the method names for unary-unary and unary-stream methods. This PR updates the server to check the method on present, which like the grpc server requires retrieving the model. Retrieving is placed in the try/catch since 404s/not founds are also returned as `CaikitRuntimeExceptions`. Further cleanup could be done in the future to make the http server more align with the grpc server.
> :bug: Allow user-defined methods for http server

- caikit/config/config.yml
- caikit/core/model_management/model_trainer_base.py
- caikit/runtime/http_server.py
- caikit/runtime/model_management/loaded_model.py
- caikit/runtime/model_management/model_loader.py
- caikit/runtime/model_management/model_manager.py
- caikit/runtime/service_generation/protoable.py
- caikit/runtime/servicers/global_predict_servicer.py
- caikit/runtime/servicers/model_runtime_servicer.py
- caikit/runtime/work_management/abortable_action.py
- caikit/runtime/work_management/call_aborter.py
- caikit/runtime/work_management/rpc_aborter.py
- tests/runtime/conftest.py
- tests/runtime/model_management/test_model_loader.py
- tests/runtime/model_management/test_model_manager.py
- tests/runtime/servicers/test_model_runtime_servicer_impl.py
- tests/runtime/test_grpc_server.py
- tests/runtime/work_management/test_abortable_action.py
- tests/runtime/work_management/test_call_aborter.py
This is a better implementation of https://github.com/caikit/caikit/pull/336
This PR adds a new feature to `caikit.runtime` to use a local directory on disk (which can be mounted) to act as a shared-state cache. This will allow replicas of `caikit.runtime` to host an eventually-consistent set of models that changes dynamically. This is a significantly weaker value proposition than `model-mesh`, but for many model types, especially those that use a `module_backend` to delegate the work to another engine (e.g. `caikit-tgis-backend`), it's fine to require that all models be loaded on all replicas.
> Lazy local model loading 324

- caikit/interfaces/nlp/tasks.py
- tests/interfaces/nlp/test_nlp_tasks.py
- tests/interfaces/nlp/test_text_generation.py
For trying to move caikit-nlp text generation modules to use the prescribed interfaces and tasks for text generation per `caikit.interfaces.nlp` in https://github.com/caikit/caikit-nlp/issues/92, tests can be moved here and `inputs` was presumably used to conform with Huggingface interfaces. However for semantically meaningful use, the modules have all used `text` as the input. With the REST server, `inputs` will be usable to align with Huggingface interfaces.
> :sparkles::white_check_mark: Use text for text generation task

- caikit/interfaces/nlp/data_model/text_generation.py
Originally the text generation interfaces in caikit were developed here in alignment with [Huggingface TGI](https://github.com/huggingface/text-generation-inference/blob/main/docs/openapi.json) but the [TGIS streaming interfaces](https://github.com/IBM/text-generation-inference/blob/main/proto/generation.proto) predate and slightly differ from TGI, with the main focus on text.
[`caikit-nlp`](https://github.com/caikit/caikit-nlp) using [caikit-tgis-backend](https://github.com/caikit/caikit-tgis-backend) has text generation module implementations that require TGIS compatibility. The stream result here has been edited for TGIS compatibility but still keeping most TGI fields, where the original TGI `token` could be one of the TGIS-compatible `tokens`.
NOTE: The current interfaces already have …
> :sparkles: Update text gen interfaces with TGIS compatibility

- caikit/core/model_manager.py
- caikit/runtime/server_base.py
- caikit/runtime/utils/import_util.py
- tests/core/test_model_manager.py
- tests/runtime/test_grpc_server.py
- tests/runtime/utils/test_import_util.py
Closes #355 
This PR moves the initialization of `caikit.core.MODEL_MANAGER` components to happen proactively when a server (`grpc` or `http`) is initialized. This means that each component instance will be instantiated in the parent thread of the server rather than in a worker thread.
> Proactive mm init 355

- caikit/interfaces/common/data_model/stream_sources.py
- caikit/runtime/service_generation/data_stream_source.py
- tests/runtime/service_generation/test_data_stream_source.py
Implements #363 , https://github.com/caikit/caikit/issues/300
This PR adds an `S3Files` source for datastreams.
This is not implemented in the core of caikit yet, we don't have support for pulling files from S3. But it's left open to extension for other projects to implement as needed.
This also removes the dynamic generation of the `Files` `ListOfFiles` and `Directory` data models, in favor of static class definitions.
> ✨ S3 streams

- caikit/config/config.yml
- caikit/runtime/grpc_server.py
- caikit/runtime/http_server.py
- caikit/runtime/model_management/model_manager.py
- caikit/runtime/server_base.py
- tests/fixtures/config/config.yml
- tests/runtime/conftest.py
- tests/runtime/test_grpc_server.py
- tests/runtime/test_http_server.py
Closes #364
This PR updates the shutdown logic in `grpc_server` and `http_server` to correctly shut down the runtime Model Manager's poll timer for lazy model loading. While I was working on this, I discovered several other bugs that needed fixing:
1. Runtime was using `runtime.port` instead of `runtime.grpc.port`
2. The prometheus metrics were _always_ booting up in the `grpc_server`'s `main()`, regardless of `runtime.metrics.enabled`
> Server shutdown with sync

- caikit/core/toolkit/destroyable_thread.py
- tests/core/model_management/test_local_model_trainer.py
- tests/core/toolkit/test_destroyable_process.py
- tests/core/toolkit/test_destroyable_thread.py
Supports #332 
This PR fixes the bug where a training run in a `DestroyableThread` can move from `COMPLETED` -> `CANCELED`
> 🐛  No canceled after completed

- caikit/config/config.yml
- caikit/runtime/server_base.py
- tests/runtime/test_http_server.py
`find_available_ports` cleanup (round 2) for #343 in line with the changes made in PR #302 
As described, the base runtime server should not have a private method to find open ports. This should only be done for unit tests, where an `open_port` fixture exists.
> :recycle: Only find open ports on tests

- caikit/core/data_model/__init__.py
- caikit/core/data_model/training_status.py
- caikit/core/model_management/__init__.py
- caikit/core/model_management/local_model_trainer.py
- caikit/core/model_management/model_trainer_base.py
- caikit/interfaces/runtime/data_model/__init__.py
- caikit/interfaces/runtime/data_model/training_management.py
- caikit/runtime/service_factory.py
- caikit/runtime/servicers/global_train_servicer.py
- caikit/runtime/servicers/training_management_servicer.py
- tests/core/helpers.py
- tests/core/model_management/test_local_model_trainer.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/servicers/test_training_management_servicer.py
- tests/runtime/test_grpc_server.py
- tests/runtime/utils/test_servicer_util.py
1.  Move `TrainingInfo` down to `caikit.core` as part of the ModelTrainer / ModelFuture api
2. Make trainers return exception instead of returning error strings
> :recycle: Move training info out of interfaces

- .gitignore
- caikit/core/model_management/local_model_trainer.py
- caikit/core/model_management/model_trainer_base.py
- caikit/core/model_manager.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/servicers/global_train_servicer.py
- caikit/runtime/servicers/model_train_servicer.py
- scripts/check_deps.sh
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tox.ini
For #369 
This PR adds `output_path: S3Path` to all train apis
This PR _does not_ nest the rest of the training parameters. That turned out to be a bit of a bear so we're following up in a separate PR.
We went with just an `S3Path` for now and not also a `str` because we already have pretty good on-disk-path support via the `runtime.training.output_dir` configuration. That allows a deployment-wide base path to be set and then the `model_name` parameter provides the directory separation within that base path on a per-training-request basis. We think some more design thought is needed if we want to start overriding disk paths directly from the training API.
This change updates the base trainer implementation to …
> Add output_path to train apis

- caikit/core/toolkit/destroyable_thread.py
- caikit/runtime/service_factory.py
- caikit/runtime/servicers/training_management_servicer.py
- tests/core/toolkit/test_destroyable_thread.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/servicers/test_training_management_servicer.py
- tests/runtime/test_grpc_server.py
Issue #332 
This PR adds:
- another rpc to `service_factory.py`, TRAINING_MANAGEMENT_SERVICE_SPEC to include a new rpc for cancelling a training. The rpc accepts a training id as input, and returns the TrainingStatus of that training as output after canceling the model future.
- implements the `CancelTraining` method in `training_management_servicer.py`.
- Tests
> Add CancelTraining to training_mangement_servicer

- caikit/core/model_management/local_model_trainer.py
- caikit/core/model_management/model_trainer_base.py
- caikit/core/model_manager.py
- caikit/runtime/servicers/global_train_servicer.py
- tests/core/model_management/test_local_model_trainer.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
For #381 
This PR adds `model_name` as an optional top-level arg to the model trainer's `.train` interface.
This allows model trainer implementations to construct their own save paths based on
- the base path given
- the training id
- the model name
The abstract base class is updated so that the save path is constructed as
```
${save_path}/${training_id}/${model_name}
```
This should not be a breaking change since the parameter is optional with a default of none
(except maybe how the .train function may have keyword collisions with actual training kwargs but... /shrug)
> :sparkles: Add model name to Trainer API

- caikit/runtime/servicers/training_management_servicer.py
- tests/runtime/servicers/test_training_management_servicer.py
This just tightens up the error handling in the training management handlers.
I'm getting a 13 response with no related logs from caikit even on debug4 so this decreases the scope of each try/catch to provide better visibility into what's going wrong.
> :goal_net: Tighter handling around training mgmt

- caikit/config/config.yml
- caikit/core/model_management/local_model_trainer.py
- caikit/core/toolkit/destroyable_process.py
- caikit/runtime/service_generation/data_stream_source.py
- caikit/runtime/utils/servicer_util.py
- tests/conftest.py
- tests/core/model_management/test_local_model_trainer.py
- tests/core/toolkit/test_destroyable_process.py
- tests/core/toolkit/test_error_handler.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/utils/test_servicer_util.py
Closes #384 
This PR makes it safe to use "spawn" when performing training jobs.
> Use spawn for train subprocess 384

- caikit/runtime/dump_services.py
- caikit/runtime/grpc_server.py
- caikit/runtime/http_server.py
- caikit/runtime/servicers/global_predict_servicer.py
- tests/runtime/conftest.py
- tests/runtime/test_http_server.py
This PR refactors the `init` function of the `http_server` to align with `grpc_server`. The idea is to eventually have a common `caikt/runtime/__main__.py` which can start both servers with similar arguments.
Alternate implementation here:  https://github.com/caikit/caikit/pull/389
Also fixes https://github.com/caikit/caikit/issues/380
> ♻️ refactor init for http (see #389 instead)

- caikit/core/model_management/local_model_initializer.py
- caikit/core/model_manager.py
- caikit/core/modules/config.py
- caikit/core/modules/loader.py
- caikit/runtime/model_management/model_loader.py
- caikit/runtime/model_management/model_manager.py
- tests/core/helpers.py
- tests/core/modules/test_module.py
- tests/core/test_model_manager.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/model_management/test_model_manager.py
Closes #394 
This PR makes it possible to write a `ModelFinder` that finds models in non-disk locations. This could be fetching a model from a remote repository or a config-only model that does not need any load-time artifacts (e.g. remote proxy to TGIS)
> Non disk lazy loading

- caikit/core/toolkit/error_handler.py
Whoops, adds back the ability to
```
from caikit.core.toolkit import error_handler
```
with warnings
> :goal_net: add more compatibility for toolkit.error_handler

- caikit/config/config.yml
- caikit/runtime/model_management/loaded_model.py
- caikit/runtime/model_management/model_loader.py
- caikit/runtime/model_management/model_manager.py
- tests/conftest.py
- tests/runtime/conftest.py
- tests/runtime/model_management/test_model_loader.py
- tests/runtime/model_management/test_model_manager.py
Closes #404 
This PR adds retry support for loading models from `local_models_dir`. This is needed to handle races with model artifact copying since an artifact will not be atomically copied to the mounted directory. If the periodic sync or a user inference request is triggered when a model is partially uploaded, the `load` function will begin, but will fail due to corrupted resources. Prior to this PR, this situation was handled by simply removing the model from the set of loaded models and letting the lazy loading restart on the next stimulus (period or inference request). The problem with this approach is that any requests received during the beginning of the load and the eventual failure/unload would receive 500 responses due to the failed load. …
> Retry load failures 404

- caikit/core/model_management/factories.py
- caikit/core/model_management/multi_model_finder.py
- caikit/core/model_manager.py
- tests/core/helpers.py
- tests/core/model_management/test_multi_model_finder.py
Supports #412 
This PR adds a `MultiModelFinder` that is capable of proxying to an ordered list of multiple finders in the `model_management.finders` section.
This will be needed in order to fully take advantage of the `TGISAutoFinder` in `caikit-nlp` ([PR](https://github.com/caikit/caikit-nlp/pull/123))
> Multi mm component 412

- caikit/core/modules/saver.py
- tests/core/modules/test_module.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
Both watson_nlp and caikit_nlp pass args to save in certain modules. 
Blocking other efforts, kindly prioritize
> update saver to take args

- caikit/runtime/http_server.py
- tests/fixtures/sample_lib/data_model/sample.py
- tests/fixtures/sample_lib/modules/other_task/other_implementation.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
- tests/runtime/test_http_server.py
fix https://github.com/caikit/caikit/issues/346
- This PR implements `ResponseValidationError` which validates the handler's `response` and enables better error message from the response validation.
- To test this, this PR also adds `ProducerId` as a required field in `OtherOutputType` and adds a poison pill within `other_implementation` so that we can test error conditions if a required field is not present. 
- This PR also adds other `http` tests to test for incorrect/missing fields in `request` messages.
- Uses [requestvalidationerror](https://fastapi.tiangolo.com/tutorial/handling-errors/#use-the-requestvalidationerror-body) documentation but for `ResponseValidationError`.
> 🥅 add better REST error handling

- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/__init__.py
- caikit/runtime/service_generation/data_stream_source.py
- caikit/runtime/service_generation/proto_package.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/utils/servicer_util.py
- tests/core/data_model/test_base.py
- tests/core/data_model/test_dataobject.py
- tests/core/data_model/test_timestamp.py
- tests/data_model_helpers.py
- tests/runtime/test_service_factory.py
In order to achieve backwards compatibility with an earlier gRPC client, I need to be able to override the domain and package names in the config file:
Example:
```
runtime:
service_generation:
package: whatever.runtime.foofoo.v0
domain: WhatEver
```
Fixes https://github.com/caikit/caikit/issues/334
> feat: Make it possible to override the domain and package names

- caikit/runtime/http_server.py
- tests/runtime/test_http_server.py
Fixes an issue when converting dataobject to pydantic models when there is inheritance involved.
fix #419 
> FYI - this has a consequence in all cases where we have derived DM objects. Instantiating any derived DM object will require that we satisfy ALL fields within the base DM object as well. (applies to `S3Path`)
- https://docs.python.org/3/library/typing.html#typing.get_type_hints
- https://peps.python.org/pep-0526/#runtime-effects-of-type-annotations
> The recommended way of getting annotations at runtime is by using typing.get_type_hints function; as with all dunder attributes, any undocumented use of __annotations__ is subject to breakage without warning:
> 🐛 Fix derived DM to pydantic conversion bug

- caikit/core/model_management/local_model_initializer.py
- caikit/core/model_manager.py
- caikit/core/modules/base.py
- caikit/runtime/model_management/model_loader.py
- tests/core/helpers.py
- tests/core/test_model_manager.py
Closes #417 
This PR fixes the overly-strict assumptions made about how `load` functions have been implemented in the wild, thus fixing backwards compatibility for recent changes to pass `ModuleConfig` as the first argument to `load`. It does so explicitly to fix backwards compatibility, so did not attempt to make anything more strict w.r.t. setting expectations about how `load` should be implemented in the future
> Module load api cleanup 417

- caikit/core/modules/base.py
The proposed change is **original watson_core order** of function args and also what is specified in docstrings. changing order in caikit can cause weird behavior in downstreams unless we all change order of arguments, which is a huge change for nLP and unnecessary
blocking NLP rebase. There were no unit tests for these functions from the start, will be a larger effort to add for all these functions in module base. 
> fix: change in function args order to _extract_pred_set

- caikit/core/data_model/dataobject.py
- pyproject.toml
- tests/core/data_model/test_dataobject.py
- tests/runtime/test_http_server.py
Closes #437 
This PR also stumbled on a fuuuun bug: We were never checking the output format of server-side streaming with SSE. Turns out it was just calling `__repr__` on each yielded data object which was returning as `"MyDataObject(foo=1)"` rather than the `json` version `{"foo": 1}`. This made the HTTP output stream virtually useless! Updating the base `__repr__` fixes this, so this PR also fixes the test for server side checking to make sure the output is `json` parsable.
> Don't overwrite the __repr__ with dataclass and fix HTTP output format

- caikit/runtime/grpc_server.py
When we added the `runtime.grpc` level of indentation in config for the `grpc/http` split, we missed this log message!
> 🐛  ServerBootLogMessage: Use the right config path in the log message!

- pyproject.toml
Minor fix to `pyproject.toml` to fix the `requires-python` value
> Update requires-python for 3.8+

- caikit/core/registries.py
- caikit/runtime/service_factory.py
- tests/conftest.py
- tests/core/helpers.py
- tests/core/module_backends/test_backend_types.py
- tests/core/modules/test_module.py
- tests/core/test_model_manager.py
- tests/runtime/model_management/test_model_loader.py
- tests/runtime/service_generation/test_create_service.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_service_factory.py
Fixes #446 
This includes backend modules in the service generation.
It also fixes our `reset_globals` fixture since that wasn't properly cleaning up backend modules.
It also moves the `reset_*` stuff into `conftest.py` so that
- We don't need squirrely imports in our tests, and
- The runtime tests can use them too
> 🐛  Backends fix

- caikit/runtime/http_server.py
- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/servicers/global_train_servicer.py
- caikit/runtime/servicers/model_train_servicer.py
- tests/runtime/service_generation/test_rpcs.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/servicers/test_model_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
- tests/runtime/test_http_server.py
- tests/runtime/utils/test_servicer_util.py
POC for #369 
This updates the training RPC to manage an inner and outer request message, and it seems to work pretty slick.
cc @gabe-l-hart, @gkumbhat and @prashantgupta24 I think this'll work if we wanted to rip the bandaid on doing this nesting so we can have the pydantic apis convert these data models directly on the http side as discussed.
Open problem now is getting the caikit user access to the inner data model type so they can construct one of these messages directly. But running via compiled protobuf or REST that won't be an issue.
> Update - the `client_module` has been updated to incorporate ALL DM objects, so that unit tests as well as users can fetch the inner Proto message from it.
Pending pydantic …
> ♻️  split training parameters

- caikit/core/data_model/base.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/http_server/pydantic_wrapper.py
- tests/conftest.py
- tests/fixtures/models/box/config.yml
- tests/fixtures/sample_lib/data_model/sample.py
- tests/fixtures/sample_lib/modules/__init__.py
- tests/fixtures/sample_lib/modules/file_processing/__init__.py
- tests/fixtures/sample_lib/modules/file_processing/bounding_box_module.py
- tests/runtime/conftest.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/http_server/test_pydantic_wrapper.py
This PR updates the `http_server` runtime to directly call a data object's `to_json` function before returning the fastapi Response. This allows users to customize a models json representation instead of defaulting to fastapi's [jsonable_encoder](https://fastapi.tiangolo.com/tutorial/encoder/?h=jsonable_enc#using-the-jsonable_encoder)
This is my first PR to caikit so please let me know if there is anything I should do differently!
> Convert to json before returning fastapi response

- caikit/core/data_model/base.py
- tests/core/data_model/test_dataobject.py
This PR adds a couple of test cases to make sure that #460 (round tripping a DM object with bytes) works fine if we explicitly declare a `bytes` object.
There was quite a bit of back-and-forth regarding this PR. I will try to summarize the discussion.
When Gabe created the issue #460, he tried to create a DM object having a `bytes` field with a `string`, and that was failing. In the original implementation to fix this, I manually checked if the object type was a `string` and the field type was `bytes`, and I explicitly converted the `string` to `bytes`, which made the failing test work.
However, Gabe pointed out that if we go down this route, this type of conversion will have to be done holistically, which …
> 🐛 fix Data model objects with Bytes bug

- caikit/config/config.yml
- caikit/runtime/grpc_server.py
- tests/runtime/test_grpc_server.py
Closes: #465 
This PR adds a new config section `runtime.grpc.options` that allows arbitrary key/value overrides with `grpc` server options.
> GrpcServerOptions: Add runtime.grpc.options to support server options

- caikit/runtime/servicers/global_train_servicer.py
- caikit/runtime/servicers/model_train_servicer.py
- tests/runtime/servicers/test_model_train_servicer_impl.py
**NOTE**: This is an API breaking change as it will change the behavior of training jobs to result in models failing to be updated unless corresponding changes are made in the server's config to set `runtime.training.output_dir` to `""`.
Closes #478 
This PR adjusts the behavior of the Model Train servicer so that if `runtime.training.output_dir` is configured in the global config, the model will be saved there rather than in `request.training_output_dir`. This is needed to support the usecase of saving models to mounted PVCs rather than uploading them to S3 when S3 is not available.
> Mt save path 478

- caikit/runtime/servicers/global_train_servicer.py
- caikit/runtime/servicers/model_train_servicer.py
- tests/runtime/servicers/test_model_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
This PR modifies the `model_train_servicer` to use the inbound `ProcessRequest`'s `customTrainingID` if given. It is needed so that the fully-external `caikit` ID can be used in the save path.
> Model train save with custom

- caikit/runtime/http_server/http_server.py
- tests/runtime/http_server/test_http_server.py
The uvicorn server uses python's SslContext which requires tls files be on disk and not passed by value.
Closes: https://github.com/caikit/caikit/issues/477
This PR updates the logic for booting the `uvicorn` server so that if the configured TLS values are passed as inline values, they will be temporarily written to a file so that they are loaded correctly. This is needed because [uvicorn uses `ssl.SslContext`](https://github.com/encode/uvicorn/blob/master/uvicorn/config.py#L110) to manage is TLS connection and that loads values from disk only.
> HTTP With mTLS Inline

- caikit/runtime/http_server/pydantic_wrapper.py
- tox.ini
Pydantic [protected namespaces](https://docs.pydantic.dev/latest/api/config/#pydantic.config.ConfigDict.protected_namespaces) raised warnings as per #448. 
This PR resolves the warning and closes #448 (along with a couple of typo fixes).
> Handle Pydantic "model_" conflict warning

- caikit/core/modules/base.py
The previous [PR](https://github.com/caikit/caikit/pull/432/files) removed `*args` from `def _extract_pred_set()` signature. This PR will remove `*args` where `_extract_pred_set()` is called. Additionally since `*args` is no longer used above this can be removed from `evaluate_quality()` params as well.
This update was  tested in Watson NLP.
> remove unused '*args'  when calling _extract_pred_set()

- caikit/core/toolkit/destroyable_process.py
- tests/conftest.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/servicers/test_global_train_servicer_impl_subprocess.py
- Change `OOM_EXIT_CODE` to a list (and change variable name accordingly)
- Add 9, -9 to OOM exit code list (generally unsigned exit codes are expected but -9 has appeared before)
> :wrench: Add 9 as another OOM indicative exit code

- caikit/runtime/model_management/model_manager.py
Just looking around at timers for other reasons and I noticed that the lazy load poll timer is not set as a daemon. I think we'd want this set so that we don't have a child thread here interfering with shutdown.
> :sparkles: set timers to daemon

- caikit/core/data_model/streams/data_stream.py
- caikit/runtime/service_generation/data_stream_source.py
- caikit/runtime/servicers/global_train_servicer.py
- tests/core/data_model/streams/test_data_stream.py
- tests/runtime/service_generation/test_data_stream_source.py
Closes #500 - previously users would just receive an empty stream for non-array JSON provided in JSON files. This PR provides users an error message when an array is expected
Includes small duplicate log code update
> :goal_net: Return error for non-array JSON where array is expected

- caikit/core/data_model/base.py
- caikit/runtime/service_generation/data_stream_source.py
- tests/core/data_model/test_dataobject.py
- tests/runtime/service_generation/test_data_stream_source.py
Closes #513 
- Users want to be able to provide training data files with extra fields that might not be strictly necessary for the training process without erroring
- Re-orders the methods tried for parsing data source files without extensions to allow multiparts to be tried first, otherwise they may be incorrectly attempted to be parsed by other methods - note: this does not address "missing" data model fields being represented as null since [protobuf is used to parse json](https://github.com/caikit/caikit/blob/b5c12d7bd93db40b6f53e9cef6e90be8113fe538/caikit/core/data_model/base.py#L765-L767)
- Removes some unneeded test fixture parameters
> :sparkles: Allow for extra fields in data sources

- caikit/core/data_model/base.py
- tests/core/data_model/test_dataobject.py
Addresses: https://github.com/caikit/caikit/issues/443
Adds some additional checks in `DataBase.from_proto()` to ensure that we only apply sequence-specific logic to sequences that were generated by `py_to_proto` not data objects which happen to have names ending in "sequence".
Some unit tests were added to test the added functionality on edge cases which previously failed.
> Fix DataObjects with Sequence in names

- caikit/runtime/types/caikit_runtime_exception.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/servicers/test_model_train_servicer_impl.py
- tests/runtime/types/test_caikit_runtime_exception.py
fix https://github.com/caikit/caikit/issues/501
There were 2 issues identified:
1. The tests in `test_model_train_servicer_impl.py` were not using `sub-process` correctly  since the `get_trainer` function always fetches a trainer that was initialized before our custom config (with `sub_process` set to `True`) comes into play. Hence we’re never actually checking a training in a `sub_process`. I verified this by running a failing test and seeing that we always hit `destroyable_thread.py` in the stacktrace instead of `destroyable_process` in both scenarios.
2. `CaikitRuntimeException` was not pickleable, which is a requirement for any object to be passed through sub-processes using `Pipe()`. 
> 🐛 Propagate sub-process errors properly

- caikit/core/modules/base.py
- caikit/core/modules/decorator.py
- caikit/core/modules/meta.py
- caikit/core/task.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/create_service.py
- caikit/runtime/service_generation/rpcs.py
- caikit/runtime/servicers/global_predict_servicer.py
- caikit/runtime/servicers/global_train_servicer.py
- examples/text-sentiment/client.py
- tests/conftest.py
- tests/core/test_task.py
- tests/fixtures/models/multi/config.yml
- tests/fixtures/sample_lib/modules/__init__.py
- tests/fixtures/sample_lib/modules/multi_task/__init__.py
- tests/fixtures/sample_lib/modules/multi_task/multi_task_module.py
- tests/runtime/conftest.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/service_generation/test_create_service.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
- tests/runtime/test_service_factory.py
refs #246 
Today Caikit allows only a single task to be associated with a module. However, some ML models may support multiple tasks. For example, a multi-modal model may support inference tasks for each data modality. The only way to achieve this currently is to create two modules, and a model that refers to each of them. This means the model weights may be loaded twice, wasting memory. 
This PR implements multi-task support as follows:
- A new optional `tasks` parameter on `@module` allows you to specify a list of tasks. This takes precedence over `task`.
- Inference methods for each task are annotated with `@TaskClass.taskmethod()`.
- As a consequence of this, some of the task validation is relaxed as it's now valid to have multiple tasks …
> Suport modules with multiple tasks

- caikit/runtime/service_factory.py
- caikit/runtime/service_generation/rpcs.py
Quick follow-on to https://github.com/caikit/caikit/pull/511
Adds a few comments and a warning log in the service generation bits for the `training` endpoint when you have a multi-task model.
> :loud_sound: add comments, warning for multi-task train

- caikit/config/config.yml
- caikit/core/model_management/factories.py
- caikit/core/toolkit/factory.py
- caikit/runtime/service_generation/data_stream_source.py
- docs/adrs/022-pluggable-runtime-io.md
- tests/data_model_helpers.py
- tests/runtime/service_generation/test_data_stream_plugins.py
- tests/runtime/service_generation/test_data_stream_source.py
Addresses #517 
This PR refactors `DataStreamSource` to us a pluggable/extensible factory pattern to allow for external library extensions. Concretely, this adds the following:
* New config section `data_streams.source_plugins` to define the set of source plugins
* The keys in this map are arbitrary labels that are used for logging, but nothing else. Do we like this?
* New base class (`DataStreamSourcePlugin`) that can be extended for new plugins
* New factory for stream source plugins
The ADR also contains details about plans to handle pluggable output with `OutputTarget`s, though those are not implemented in this PR
> Pluggable data input

- caikit/core/data_model/base.py
- caikit/interfaces/common/data_model/__init__.py
- caikit/interfaces/common/data_model/file.py
- caikit/interfaces/common/data_model/stream_sources.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/http_server/pydantic_wrapper.py
- caikit/runtime/http_server/utils.py
- caikit/runtime/service_generation/data_stream_source.py
- caikit/runtime/servicers/model_train_servicer.py
- tests/fixtures/sample_lib/data_model/sample.py
- tests/fixtures/sample_lib/modules/file_processing/bounding_box_module.py
- tests/fixtures/sample_lib/modules/multi_task/multi_task_module.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/http_server/test_pydantic_wrapper.py
- tests/runtime/http_server/test_utils.py
- tests/runtime/service_generation/test_create_service.py
- tests/runtime/service_generation/test_data_stream_plugins.py
- tests/runtime/service_generation/test_data_stream_source.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
- tests/runtime/servicers/test_global_train_servicer_impl.py
- tests/runtime/servicers/test_model_train_servicer_impl.py
- tests/runtime/test_grpc_server.py
- tests/runtime/utils/test_servicer_util.py
This PR adds support for multi-part input and binary file output in the HTTP server. This allows users to submit requests via json or multi-part/form-data. The form-data is structured so that each key is the subpath where the value should live. For example the following form-data:
```
----
inputs.name
"test"
---
inputs.other
"test2"
---
parameters
'{"json":"field"}'
```
Would be parsed into the following structure:
```
{
"inputs":{
"name":"test",
"other":"test2"
},
"parameters":{
"json":"field"
}
}
```
The Binary file output is controlled via two new optional methods on `DataObjectBase`: `to_file` and `from_file`. If these functions are implemented then the HTTP server will automatically return a bytes file using `to_file`. Currently this …
> Add Support for Multi-Part Input and Binary File Output in HTTP Server

- caikit/runtime/service_generation/create_service.py
- tests/runtime/service_generation/test_create_service.py
When generating inference rpcs, we use `modules` as a set, not a list, so the order of modules could be undeterministic. 
This PR sorts that modules list by Module ID so the list is fixed and deterministic.
Ex: SampleTaskRequest contains inference signatures from ListModule, SampleModule, PrimitiveSampleModule. Because this is a set of modules, it depends on which module is processed first, SampleTaskRequest will have different field ordering.
May be one of the fixes for https://github.com/caikit/caikit-nlp/issues/237.
> Sort Modules in inference rpcs generation

- .github/workflows/publish-library.yml
- .gitignore
- caikit/__init__.py
- caikit/version.py
- pyproject.toml
- tox.ini
As discussed in https://github.com/caikit/caikit-nlp/pull/216, this moves the build system to `setuptools`, providing automatic version discovery from git tags using `setuptools-scm`
> use setuptools/setuptools-scm

- caikit/runtime/grpc_server.py
- tests/runtime/test_grpc_server.py
This PR updates the GRPCServer unix socket implementation to actually allow listening over unix sockets. Prior to this the server would always skip adding the unix socket even if the target directory existed.
> Fix GRPC server over Unix socket

- tests/runtime/http_server/test_http_server.py
This PR adds:
- A fixture for the `fastapi.testclient`
- Skips testing streaming cases with FastAPI's testclient, pending resolution of https://github.com/tiangolo/fastapi/discussions/10518
- Instead, test streaming tests against an actual server.
fix https://github.com/caikit/caikit/issues/540
- Following suggestions from:
-  https://github.com/encode/starlette/issues/1315#issuecomment-1166600293 
- https://github.com/sysid/sse-starlette/issues/68#issuecomment-1678266759
> 🐛 Stream test bug fix

- caikit/runtime/http_server/http_server.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/http_server/test_http_server.py
This PR makes 2 changes:
Right now in streaming APIs, we only sent in the `data` but not the type of event.
```
data: {
data:   "greeting": "Hello world stream"
data: }
```
Users could not determine whether an event was an error or a message.
This PR adds a `event` type to the messages, so that they look like:
```
event: message
data: {"greeting": "Hello world stream"}
```
or
```
event: error
data: {"details": "ValueError('raising a ValueError')", "code": 400}
```
This PR also makes the `http_server` catch `TypeError, ValueError` type errors, so that they are now tagged with `400`s instead of `500`s which was happening before and which was incorrect. Currently, in case of streaming, if the error happens while the stream is consumed, the error …
> ✨ add stream event types

- caikit/runtime/service_generation/create_service.py
- tests/runtime/service_generation/test_create_service.py
Follow up on #535, we also should make the service generation deterministic by sorting rpcs by name.
This PR sorts rpcs (both inference and training) and fixes unit tests.
Part of https://github.com/caikit/caikit-nlp/issues/237 
> Order rpcs by name

- caikit/runtime/dump_services.py
- caikit/runtime/grpc_server.py
When training is NOT enabled, we should be able to call `python3 -m caikit.runtime.dump_services [output_dir]` without any error. Right now, the code calls `get_service_interfaces` for training service too even if training is not enabled. Error:
```
[app@2435cb980b26 ~]$ python3 -m caikit.runtime.dump_services output_protos
{"channel": "COM-LIB-INIT", "exception": null, "level": "info", "log_code": "<RUN11997772I>", "message": "Loading service module: watson_nlp", "num_indent": 0, "thread_id": 140167956726016, "timestamp": "2023-10-26T17:55:40.602909"}
Traceback (most recent call last):
File "/usr/lib64/python3.8/runpy.py", line 194, in _run_module_as_main
return _run_code(code, main_globals, None,
File "/usr/lib64/python3.8/runpy.py", line 87, in …
```
> Only call get_service_package for TRAINING when train is enabled

- caikit/interfaces/nlp/data_model/classification.py
- caikit/interfaces/nlp/data_model/text.py
- Add `start_index` as additional field to allow easy use of processed classification results instead of referencing it from "end" index with `processed_index`
> :technologist: Add start_index in response

- caikit/core/data_model/streams/data_stream.py
- caikit/runtime/service_generation/data_stream_source.py
- tests/core/data_model/streams/test_data_stream.py
- tests/runtime/service_generation/test_data_stream_source.py
We came across two issues while testing custom plugins for DataStreamSources:
1. The `.to_data_stream` method is called on each read through the stream, which is really slow when your plugin implementation is reading from a remote resource, and unnecessary when your plugin already cached the remote data locally for stream re-entrancy.
2.  Calling `len` on unpickled DataStreamSources fails, because the base `DataStream` class sets a `_length` attribute that is not re-created on the DataStreamSourceBase's `__set_state__`
This PR caches both the `_length` property and the result of calling `to_data_stream` to fix both
> :zap::bug: Add proper caching of streams in sources

- caikit/runtime/model_management/model_loader.py
- tests/core/model_management/test_multi_model_finder.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/model_management/test_model_loader.py
- tests/runtime/test_grpc_server.py
In case of `local_model_finder`, if we send in a non-existent model, it throws a `FileNotFoundError` if the model_path is not found - https://github.com/caikit/caikit/blob/main/caikit/core/model_management/local_model_finder.py#L71
`multi_model_finder` on the other hand, returns a `None` if the model is not found - 
https://github.com/caikit/caikit/blob/main/caikit/core/model_management/multi_model_finder.py#L137
This was causing a scenario to occur in which `multi_model_finder` was throwing a 500 if we sent it a non-existent model:
> {"channel": "MODEL-LOADER", "exception": "Traceback (most recent call last):\n  File \"/home/runner/work/caikit/caikit/caikit/runtime/model_management/model_loader.py\", line 118, in _load_module\n    model = …
> 🐛 return 404 instead of 500 for incorrect model id with multi model finder

- caikit/runtime/dump_services.py
- examples/sample_lib/start_runtime_with_sample_lib.py
- tests/runtime/test_dump_services.py
Currently, test_dump_services.py calls `dump_grpc_services` and this function always prints out a `modules.json` file. This PR makes this an argument, and don't print out a `modules.json` file in unit tests, only in `start_runtime_with_sample_lib.py` do we want this file printed out
> Remove modules.json from tests

- examples/text-sentiment/client.py
The text-sentiment example HTTP client uses the wrong HTTP path to query caikit, leading to a 404 not found error:
```
Text: I am not feeling well today!
RESPONSE from HTTP: {
"detail": "Not Found"
}
Text: Today is a nice sunny day
RESPONSE from HTTP: {
"detail": "Not Found"
}
```
This PR fixes the request so that the output becomes:
```
Text: I am not feeling well today!
RESPONSE from HTTP: {
"classes": [
{
"class_name": "NEGATIVE",
"confidence": 0.9997759461402893
}
]
}
Text: Today is a nice sunny day
RESPONSE from HTTP: {
"classes": [
{
"class_name": "POSITIVE",
"confidence": 0.999869704246521
}
]
}
```
> fix text-sentiment example http runtime client

- caikit_health_probe/__main__.py
- pyproject.toml
- tests/runtime/conftest.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/test_caikit_health_probe.py
This PR fixes the `caikit-health-probe` to support probing a (m)TLS server over `gRPC` when the server's cert does not contain `localhost` as a Subject Alternate Name.
This PR does introduce a dependency on `cryptography` which is a widely used third party library in the python ecosystem. The need for `cryptography` stems from the fact that `grpc` does not allow TLS hostname verification to be fully disabled on the client side. As such, we need to parse the correct `hostname` override from the server's cert in order to set the value correctly in the client. There are numerous libraries to do this, and [it is technically possible using the builtin `ssl`](https://stackoverflow.com/a/50072461), but that requires …
> Health probes no localhost

- caikit_health_probe/__main__.py
- pyproject.toml
- tests/runtime/conftest.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/test_caikit_health_probe.py
This PR is one more attempt to build a robust `caikit-health-probe`, but this time without relying on the `cryptography` package. The decision to not add `cryptography` as a dependency is based on the significant security surface opened up by having this tool in the dependency chain.
With this PR, the health probe can fail when `localhost` is not in the CN/SANs for he server's cert AND the server is not running with the insecure unix socket open. This is an acceptable limitation to trade for not adding a crypto-sensitive library in the dependency list.
> No crypto health probes

- caikit/runtime/http_server/http_server.py
This PR updates the default Swagger UI Content-Type from application/json to multi-part form. Multi-part form is significantly easier to use in the UI and in most cases more performant, especially when dealing with bytes or File data. This does not affect the generated openapi spec.
This is purely a UI preference change.
> Set default Swagger UI Content-Type to multi-part form

- caikit/runtime/model_management/model_manager.py
- tests/runtime/model_management/test_model_manager.py
This PR makes it possible to load nested models inside of `local_models_dir` without them being immediately unloaded by the periodic sync logic.
This _does_ change a log code from `W` to `D` because we're changing the semantics of finding non-model directories in `local_models_dir` from being "bad" to being expected. It does NOT silence `COR80419785E` which is raised [here](https://github.com/caikit/caikit/blob/main/caikit/core/model_manager.py#L280). From the perspective of `load`, this _is_ an error, but when used by `runtime` it is a valid outcome of attempting to load something that isn't actually a model.
The fix I attempted for this was to [filter `disk_models`](https://github.com/caikit/caikit/blob/main/cai …
> Nested model names

- caikit/runtime/model_management/model_manager.py
- caikit/runtime/servicers/model_runtime_servicer.py
- tests/runtime/model_management/test_model_manager.py
- tests/runtime/servicers/test_model_runtime_servicer_impl.py
This PR addresses a race condition that was showing up due to another bug where models in the `local_models_dir` that were nested inside subdirectories were auto-unloaded when the sync cron fired. Because of how often models were being unloaded, it was reasonably common that a model would be unloaded _after_ being added to the global `self.loaded_models` map, but _before_ the `retrieve_model` call finished, causing [the re-lookup](https://github.com/caikit/caikit/blob/main/caikit/runtime/model_management/model_manager.py#L413) to raise a `KeyError`.
The fix in this PR is to not re-index into `self.loaded_models`. This does still expose the possible race condition where a request might appear as though a model were still loaded, even after it were …
> Unload model race

- tests/core/data_model/test_json_dict.py
- tests/fixtures/sample_lib/data_model/sample.py
Fix test_dict_to_struct_to_dict for proto3 issue.
Adding a dataobject that uses JsonDict made the instanceof tests
fail on proto3 due to the use of the temporary descriptor pool.
This only impacted proto3.
This is a minimal change that I'm expecting to reproduce a fail the proto3 CI tests.
I need to get past that fail for other reasons.  This sample object should help isolate/fix/test.
> Fix test_dict_to_struct_to_dict for proto3 issue

- caikit/core/modules/saver.py
- tests/core/modules/test_module.py
The prior implementation was dangerous because it could remove existing files including existing models or any accidental path passed in. This is a bit safer.
Fixes #525
> Add exist_ok option to ModuleSaver and only rmtree when exist_ok=False

- caikit/config/config.yml
- caikit_health_probe/__main__.py
This PR makes the HTTP server's health probe timeout configurable via `RUNTIME_HTTP_PROBE_TIMEOUT`
> ConfigurableHttpProbeTimeout: Make the http health probe configurable

- caikit/config/config.yml
- caikit/runtime/model_management/model_manager.py
- tests/runtime/model_management/test_model_manager.py
This fixes an issue where the lazy load loop can load a large model that is in the progress of being written, where the module itself may gracefully handle partial model artifacts.
This is done by running two back-to-back size checks on the model directory before loading, and only loading if the sizes match. This could have performance implications for models with a very large number of file artifacts. The amount of time that needs to elapse between these two checks to correctly catch models mid-write could vary depending on the specifics about how the bytes are making it to disk.
Possibly related to #467 
This is a very simple fix, it may be _too_ simple
> Don't lazy load models that are actively being written

- pyproject.toml
This fixes RuntimeError: MODULE_ID `750cad4d-c3b8-4327-b52e-e772f0d6f311` conflicts for classes `BoundingBoxModule` and `BoundingBoxModule`
`pytest-asyncio>=0.22` results in an exception at test discovery time:
```
{"channel": "MODULE_DEC", "exception": null, "level": "error", "log_code": "<COR30607646E>", "message": "exception raised: RuntimeError('MODULE_ID `750cad4d-c3b8-4327-b52e-e772f0d6f311` conflicts for classes `BoundingBoxModule` and `BoundingBoxModule`')", "num_indent": 0, "thread_id": 7983813376, "timestamp": "2023-12-04T20:49:54.281720"}
INTERNALERROR> Traceback (most recent call last):
INTERNALERROR>   File "/Users/ghart/Projects/github/caikit/caikit/.tox/py38/lib/python3.8/site-packages/_pytest/main.py", line 271, in wrap_session …
```
> PinPytestAsyncio: Pin pytest-asyncio below 0.22

- caikit/core/model_management/factories.py
- caikit/core/model_management/multi_model_initializer.py
- tests/core/model_management/test_multi_model_initializer.py
This PR adds a `MultiModelInitializer` implementation that is very similar to the existing MultiModelFinder except that it works with initializers. This will support future initializers that might need a backup/default override. 
> Add MultiModelInitializer Implementation

- caikit/runtime/__main__.py
- caikit/runtime/grpc_server.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/server_base.py
- tests/runtime/conftest.py
- tests/runtime/test_grpc_server.py
This was a tangent I went on today. This PR both:
- allows multiple servers to cleanly register shutdown handlers for interruption
- Updates the http server hackery to ensure that previously registered signal handlers are actually invoked when uvicorn overrides all the signal handlers
This is a bit of a departure from how we were explicitly setting signal handlers in `main` methods before, but this allows us to easily handle uvicorn's insistence on overriding all signal handlers.
> :bug: ensure correct shutdown handlers called

- caikit/config/config.yml
- caikit/runtime/http_server/http_server.py
- tests/runtime/http_server/test_http_server.py
Closes #609 
This PR makes it possible to set arbitrary `uvicorn` server config overrides as long as they don't overlap with the ones that `caikit` manages explicitly.
> Uvicorn config 609

- caikit/runtime/http_server/http_server.py
- caikit/runtime/servicers/global_predict_servicer.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
Move the model lookup for inference signature into predict_model
The `retrieve_model` operation can potentially be expensive. With the `async` HTTP server, doing this outside of the `run_in_executor` call meant that the work to look up the model (and potentially wait for it to finish loading) was blocking the event loop. That work to fetch the model was _only_ being done so that the inference function could be deduced, so moving that logic inside of `predict_model` allows the lookup (and load) logic to not block the event loop.
> ModelFetchOutOfAsyncio

- docs/adrs/024-remote-module-invocation.md
This PR creates an ADR for remote model invocation. For a full list of reasoning and description of the proposed solution take a look at the ADR; however, the first paragraph of the description is copied here for convenience:
> We propose implementing a system for remote model invocation directly in the Caikit core library. 
This system will handle discovering and loading models from a remote runtime. These remote modules 
will look and function like local modules, except any task or train invocation is forwarded to the 
remote. The core components of this system will be a new ModelFinder named RemoteModelFinder and a 
new ModelInitializer called RemoteModelInitializer.
This ADR assumes the functionality provided …
> Propose RemoteModelInvocation ADR

- caikit/runtime/http_server/http_server.py
Refactors (#610) removed the host argument to the uvicorn config, causing the http server to only bind to 127.0.0.1.
> re-expose http server

- caikit/core/modules/base.py
- caikit/interfaces/runtime/data_model/__init__.py
- caikit/interfaces/runtime/data_model/info.py
- caikit/runtime/http_server/__init__.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/service_factory.py
- caikit/runtime/servicers/info_servicer.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/test_grpc_server.py
This PR allows for end-users to get information about the currently loaded models. This includes things like the model name, path, version, and size. The information is gathered from the `runtime.ModelManager.loaded_models` values.
This endpoint will be useful for the RemoteModel work and for any thin-client to discover models.
> Add endpoint to get information about loaded models

- caikit/runtime/model_management/model_loader.py
- caikit/runtime/model_management/model_manager.py
- tests/runtime/model_management/test_model_manager.py
This PR adds two optional parameters `finder` and `initializer` to the `RuntimeModelManager.load_model` function. This allows end users to customize which finder/initializer is being used similarly to the core `MODEL_MANAGER.load` function.
> Add Finder/Initializer options to Runtime Model Manager load

- caikit/config/config.yml
- caikit_health_probe/__main__.py
- pyproject.toml
- tests/runtime/test_caikit_health_probe.py
Closes #635 
This PR expands the `caikit_health_probe` tool to allow for separate `liveness`/`readiness` semantics. The former `health_probe` is converted to `readiness_probe` and a new `liveness_probe` is added. To select a probe type, add the type (`liveness` or `readiness`) to the `python -m caikit_health_probe` command.
In addition to the new `liveness` probe, this PR adds the `runtime.grpc.probe_timeout` config argument which can be used to set a timeout for the grpc `readiness` probe. It defaults to `null` so the default behavior will not change during startup.
The change is non-breaking since the default behavior of `python -m caikit_health_probe` is equivalent to `python -m caikit_health_probe readiness`. …
> Liveness probe 635

- caikit/core/model_management/multi_model_initializer.py
- tests/core/model_management/test_multi_model_initializer.py
This PR fixes a small bug which would break the MultiModelInitializer when loading from config. This also updates the test cases to hopefully avoid this issue in the future
> Fix Initialization bug in MultiModelInitializer

- caikit/core/task.py
- tests/core/test_task.py
Currently there's a bug in the way that we validate module signatures against task definitions when both contain union typed args. The main inconsistency is as follows:
- Say that a module has param named `inputs`, which is of type `Union[int, str, bytes]`
- Now say that this module implements task `Foo`. If `Foo` defines:
- `inputs` as a an `int`, `str`, OR, `bytes`, everything is happy
- `inputs` as a `Union` containing some subset of these types, everything explodes with a TypeError
This behavior should be allowed, because in some cases, the module may have args that aren't directly compatible with the base data model, e.g., types supported by the Image data model backend, namely PIL image. We should be able to pass these in at the library level, …
> Fix union validation

- caikit/core/toolkit/name_tools.py
- caikit/runtime/grpc_server.py
- caikit/runtime/servicers/global_train_servicer.py
- caikit/runtime/utils/import_util.py
- tests/runtime/utils/test_import_util.py
This PR enables the usage of `__main__` as the `runtime.library` so that an end-to-end example of `caikit.runtime` can be contained in a single python script.
While not strictly necessary for standard operation, this PR is worth merging because (a) it helps with concise examples and (b) users _may_ want to write this kind of single-module server in the future.
> Single module server

- caikit/interfaces/runtime/data_model/info.py
- caikit/runtime/model_management/loaded_model.py
- caikit/runtime/servicers/info_servicer.py
- tests/runtime/model_management/test_model_loader.py
- tests/runtime/test_grpc_server.py
Closes #653 
This PR adds a new `loaded` field to the output of each model info block behind the `InfoServicer`'s model info endpoint/rpc
> Model info loaded 653

- caikit/core/model_management/local_model_trainer.py
- tests/core/model_management/test_local_model_trainer.py
Closes #656 
This PR handles the edge case where an external job manager attempts to retry a training job against a running instance of the `LocalModelTrainer` using the same ID as a previously failed run.
> UUID asssertion on terminal 656

- caikit/runtime/grpc_server.py
- caikit_health_probe/__main__.py
- tests/runtime/conftest.py
- tests/runtime/test_caikit_health_probe.py
- tests/runtime/test_grpc_server.py
Closes #646 
Second attempt to solve the flakey port collision tests!
> FlakeyTestsRandomPorts: Use internal open-port function

- caikit/config/config.yml
- caikit/runtime/model_management/model_manager.py
- tests/runtime/model_management/test_model_manager.py
Closes #661 
This PR adds the `runtime.load_new_local_models` config option which can disable loading new models during synchronization with `local_models_dir`.
When loading new local models is disabled, the model info endpoints are not guaranteed to be consistent across replicas of `caikit.runtime` running behind a loadbalancer (e.g. k8s `Deployment` / `Service`) since loading only happens on inference calls which are distributed across the replicas.
> Proactive load toggle 661

- caikit/interfaces/nlp/data_model/embedding_vectors.py
- caikit/interfaces/nlp/data_model/reranker.py
- caikit/interfaces/nlp/data_model/sentence_similarity.py
- tests/interfaces/nlp/test_reranker.py
A requirement for https://github.com/caikit/caikit-nlp/pull/334
Adds `input_token_count` to the results data models. This allows for metrics / billing on the size of each task to be collected.
> Add input token count to embedding, reranker, sentence similarity

- caikit/interfaces/nlp/data_model/classification.py
- caikit/interfaces/nlp/data_model/text_generation.py
Add support for ReturnOptions, GeneratedTokens and InputTokens
As part of caikit there are some parameters that are hard-coded to default values in code.
In the TGIS implementation, users can set these options and get the appropriate response. 
The parameters in questions are part of the `ResponseOptions` proto found [here](https://github.com/IBM/text-generation-inference/blob/main/proto/generation.proto). 
This PR updates the data-model so that the return from inference server can be part of the result if the appropriate parameter is set in caikit FastAPI endpoint.
> Add support for ReturnOptions, GeneratedTokens and InputTokens

- caikit/core/exceptions/error_handler.py
- caikit/core/exceptions/validation_error.py
- caikit/core/toolkit/factory.py
`ErrorHandler` is used extensively in the caikit ecosystem. Adding typing to `caikit.core.exceptions` provides quality of life code completion benefits for the popular `ErrorHandler.XXX_check` methods.
> Add typing to caikit.core.exceptions

- caikit/runtime/client/remote_model_finder.py
- tests/runtime/client/test_remote_model_finder.py
Closes #680 
This PR adds support to the `caikit.runtime.client.RemoteModelFinder` so that it can find models across multiple remote `caikit.runtime` servers. There are two new ways to enable multi-connection finding:
1. The `config.connection.hostname` string can contain a single `{}` template that will be replaced with `model_id`.
2. The `config.remote_connections` entry can be a list of connection blobs, each one with the same set of arguments as `config.connection` (`hostname`, `port`, `tls`, `options`).
Here's an example of a full configuration with `RemoteModelFinder`, `LocalFinder`, and [TGISAutoFinder](https://github.com/caikit/caikit-nlp/blob/main/caikit_nlp/model_management/tgis_auto_finder.py):
```yaml
model_management:
initializers: …
```
> Multi connection remote model finder 680

- caikit/core/data_model/dataobject.py
- caikit/runtime/dump_services.py
- examples/sample_lib/README.md
- examples/sample_lib/client_proto.py
- examples/sample_lib/start_runtime_with_sample_lib.py
- tests/runtime/conftest.py
- tests/runtime/test_dump_services.py
Closes #685 
This PR adds two new options to `caikit.runtime.dump_services`:
* `-c | --clean`: Clean out existing content in output dir
* `-p | --consolidate-packages`: Consolidate protobufs by package
The second is the primary point of this PR. It _drastically_ reduces the clutter in the dumped services directory and aligns more closely with standard protobuf practices to consolidate multiple objects into individual `.proto` files that are scoped by the `package`.
> Consolidated dump 685

- caikit/runtime/train.py
- tests/runtime/test_train.py
This PR adds a new module `caikit.runtime.train` which will execute a single training job. It is useful for running module train operations inside of a job orchestration framework.
```sh
LOG_LEVEL=debug3 \
LOG_FORMATTER=pretty \
PYTHONPATH=$PWD/tests/fixtures \
python -m caikit.runtime.train \
-m sample_lib.modules.sample_task.sample_implementation.SampleModule \
-n "my-model" \
-k '{"training_data": {"jsondata": {"data": [{"number": 1, "label": "foo"}, {"number": 2, "label": "bar"}]}}}'
```
> TrainEntrypoint: Add train main entrypoint script

- caikit/core/exceptions/error_handler.py
- pyproject.toml
closes https://github.com/caikit/caikit/issues/695
Update typing for `error_handler` to include [`LoggerProtocol`](https://github.com/IBM/alchemy-logging/blob/2bc2d8127ac878c55d5faa6c65c8fba31c4f1cf9/src/python/alog/protocols.py#L135). 
`LoggerProtocol` represents the interface for the stdlib `logger` class. `ALogLoggerProtocol`, which inherits from `LoggerProtocol`, will also be an acceptable argument to `error_handler.get()` and `ErrorHandler`.
> Add alog protocol support

- caikit/core/modules/decorator.py
- caikit/core/modules/meta.py
- tests/core/test_task.py
Closes #707 
This PR updates the logic for how the `ModuleClass.tasks` property is implemented. The previous use of a `set` was there to ensure uniqueness. It also had the subtle implication that all tasks are equally important to a given `ModuleClass` since a `set` does not guarantee order.
This second implication, however, was not respected in the train API generation. Since a given `ModuleClass` can have only a single `train` method, the mapping from `ModuleClass` to `task` was nondeterministic for multitask module training. With this PR, the order of `tasks` is now strictly defined to be the unique concatenation of the list of tasks in the module itself with the task lists of all parent modules in MRO.
**If …
> Multitask train modules 707

- caikit/runtime/train.py
- tests/runtime/test_train.py
Because train.py is being launched via the command line, we need to convert all thrown exceptions to exit codes. When running in a k8s container environment, the error message must also be written to the termination log.
> Add exception catching for everything in train.py

- caikit/runtime/servicers/global_predict_servicer.py
- caikit/runtime/servicers/global_train_servicer.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
After rpc errors were interpreted as caikit core exceptions in https://github.com/caikit/caikit-nlp/pull/355, when the servicers get called, these always get interpreted as `500` e.g. `{"details": "(<CaikitCoreStatusCode.INVALID_ARGUMENT: 2>, 'input tokens (3222) plus prefix length (0) must be < 2048')", "code": 500, "id": "875b83810ee04c058357eb5124c7cea8"`
Since the mapping of status codes is already present in caikit, this can be handled here.
> :goal_net: Handle caikit core exceptions in servicers

- caikit/core/signature_parsing/module_signature.py
- caikit/core/task.py
- caikit/interfaces/runtime/data_model/context.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/servicers/global_predict_servicer.py
- tests/core/test_task.py
- tests/fixtures/sample_lib/__init__.py
- tests/fixtures/sample_lib/modules/__init__.py
- tests/fixtures/sample_lib/modules/multi_task/__init__.py
- tests/fixtures/sample_lib/modules/multi_task/multi_task_module.py
- tests/runtime/client/test_remote_model_finder.py
- tests/runtime/service_generation/test_create_service.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
This PR adds a new task option to allow passing the runtime context to a module run method. This allows developers to change module logic based off the request context. For example a module could look for a HTTP header and change its internal processing.
> Add option to pass Context argument to Predict Servicer

- caikit/runtime/http_server/http_server.py
Remove the duplicate calls to _get_request_params in the unary input unary output handler in http server
closes #728 
Fix the duplicate calls to _get_request_params in the http server's unary input unary output handler.
> Remove duplicate calls to  _get_request_params in http server

- caikit/config/config.yml
- caikit/runtime/model_management/core_model_loader.py
- caikit/runtime/model_management/directory_model_sizer.py
- caikit/runtime/model_management/factories.py
- caikit/runtime/model_management/mm_model_sizer.py
- caikit/runtime/model_management/model_loader_base.py
- caikit/runtime/model_management/model_manager.py
- caikit/runtime/model_management/model_sizer_base.py
- caikit/runtime/names.py
- tests/runtime/model_management/test_model_loader.py
- tests/runtime/model_management/test_model_manager.py
- tests/runtime/model_management/test_model_sizer.py
This PR converts the `ModelLoader` and `ModelSizer` classes into abstract base classes with their own factories. This mimics the core model management classes like `ModelFinder`. 
> Add Abstractions for Runtime ModelManagement classes

- caikit/interfaces/common/data_model/remote.py
- caikit/runtime/client/remote_model_finder.py
- caikit/runtime/client/remote_module_base.py
- caikit/runtime/client/utils.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/client/test_remote_model_initializer.py
This PR adds support for retrying Remote inference requests. This functionality could be achieved by messing with the `options` arg but this new system is more explicit. The current defaults retain the existing functionality
> Add explicit Retry Options to Remote Runtimes

- caikit/core/data_model/runtime_context.py
- caikit/core/model_manager.py
- caikit/core/module_backends/base.py
- caikit/interfaces/runtime/data_model/context.py
- caikit/runtime/http_server/http_server.py
- caikit/runtime/servicers/global_predict_servicer.py
- tests/conftest.py
- tests/core/helpers.py
- tests/core/module_backends/test_module_backend_base.py
- tests/core/test_model_manager.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
The [caikit.core.module_backends](https://github.com/caikit/caikit/blob/main/docs/adrs/018-shared-backends.md) are designed to allow individual models to be executed in multiple ways, including proxying to remote services (e.g. [caikit-tgis-backend](https://github.com/caikit/caikit-tgis-backend)).
When a backend performs remote network operations, it may need to be aware of meta-content in runtime request headers (e.g. [x-route-info](https://github.com/caikit/caikit-nlp/pull/363)). Furthermore, a backend may be used during lazy model discovery (e.g. [TGISAutoFinder](https://github.com/caikit/caikit-nlp/blob/main/caikit_nlp/model_management/tgis_auto_finder.py)).
This combination of backend functionality means that the backend needs to be made aware …
> Module backend context update

- caikit/config/config.yml
- caikit/runtime/http_server/http_server.py
- caikit/runtime/names.py
- caikit/runtime/server_base.py
- caikit/runtime/servicers/global_predict_servicer.py
- caikit/runtime/trace.py
- otel_tracing_requirements.txt
- pyproject.toml
- tests/fixtures/fixtures.py
- tests/fixtures/sample_lib/modules/sample_task/sample_implementation.py
- tests/runtime/conftest.py
- tests/runtime/http_server/test_http_server.py
- tests/runtime/servicers/test_global_predict_servicer_impl.py
- tests/runtime/test_trace.py
**Scope of Change**:
caikit/runtime/servicers/global_predict_servicer.py inserted with global tracer and span with attributes
**Changes requires otel sdk and other dependent pkgs to be installed**:
CC @gabe-l-hart @gkumbhat
> first version showing how otel compliant tracing can be enabled

- caikit/runtime/dump_services.py
A previous PR [linked](https://github.com/caikit/caikit/commit/05895f374c83a7ebfc325281aac36820e4f6f6d5#) removed the usage of the `write_modules_json` flag in `dump_grpc_services` function. This breaks one of the libraries that rely on using `python3 -m caikit.runtime.dump_services /app/protos --write-modules-json` to have a `modules.json` output. This PR adds that flag back in
> Use the write_modules_json flag

- caikit/runtime/http_server/pydantic_wrapper.py
- pyproject.toml
Pydantic 2.8 changed some arg names  of `pydantic.create_model`. This PR updates caikit to use the new names and set a bound for the caikit version
> Update Pydantic  Wrapper to support Pydantic 2.8

- caikit/runtime/model_management/loaded_model.py
- caikit/runtime/servicers/info_servicer.py
- tests/runtime/model_management/test_model_loader.py
There is a bug in Caikit when a model failed to load but its `LoadedModel` instance is still marked as "loaded" because the `loaded()` check only considers if the future finished not if the model is actually loaded. This PR fixes this by adding an additional parameter `require_instance` which ensures that a local instance is actually available. 
> Fix Failed Loaded Modules being considered Ready

- caikit/core/model_management/model_trainer_base.py
- caikit/core/model_manager.py
- tests/core/helpers.py
This Pr fixes a regression with caikit 0.27 where the save_path was no longer included in the model trainer future base.
> Fix regression in model trainer

- caikit/core/model_management/local_job_base.py
- tests/core/model_management/test_local_model_trainer.py
This bug fixes a bug in the local model trainer where old models couldn't be purged 
> Fix bug in job predictor when model_path is folder

- .github/workflows/build-library.yml
- tests/examples/test_examples.py
Related to https://github.com/caikit/caikit/pull/769
This PR swaps the builds to use `uv`, via the `tox-uv` plugin. This should result in faster dependency resolution
> :alembic: use tox-uv for builds

- .github/workflows/build-library.yml
- .github/workflows/publish-library.yml
With v0.28.0 tag Github action to publish the wheel on Pypi is failing with following error :
```
CMake Error at CMakeLists.txt:268 (find_package):
By not providing "FindArrow.cmake" in CMAKE_MODULE_PATH this project has
asked CMake to find a package configuration file provided by "Arrow", but
CMake did not find one.
Could not find a package configuration file provided by "Arrow" with any of
the following names:
ArrowConfig.cmake
arrow-config.cmake
```
Python 3.13.3 is the new Stable release which is automatically picked by Setup Python Step(`actions/setup-python@v3`). Many Python packages (like pyarrow, pandas, and numpy) are still not support it. With this PR I had hardcode the Python version to `3.12`.
**If …
> Set Python version to 3.12 in publish action
